// ALTER SYSTEM — AlterSystemSetConfigFile (guc.c:4607) plus its helpers
// write_auto_conf_file (guc.c:4469) and replace_auto_config_value (guc.c:4537).

use std::cmp::Ordering;

use elog::ereport;
use guc::name::guc_name_compare;
use guc_file::{ConfigVariable, ParseConfigFp, CONF_FILE_START_DEPTH};
use types_error::{
    PgError, PgResult, ERRCODE_CANT_CHANGE_RUNTIME_PARAM, ERRCODE_CONFIG_FILE_ERROR,
    ERRCODE_FEATURE_NOT_SUPPORTED, ERRCODE_INSUFFICIENT_PRIVILEGE, ERRCODE_INVALID_PARAMETER_VALUE,
    ERROR, LOG,
};
use types_guc::{GUC_DISALLOW_IN_AUTO_FILE, GUC_DISALLOW_IN_FILE, PGC_INTERNAL, PGC_S_FILE};
use types_nodes::parsenodes::{AlterSystemStmt, VariableSetKind, ACL_ALTER_SYSTEM};

use crate::ExtractSetVariableArgs;

// PG_AUTOCONF_FILENAME (utils/conffiles.h).
const PG_AUTOCONF_FILENAME: &str = "postgresql.auto.conf";
// AutoFile (storage/lwlocklist.h index 35).
const AUTO_FILE_LOCK: usize = 35;
const ACLCHECK_OK: i32 = 0;

// escape_single_quotes_ascii (src/port/quotes.c): double single quotes and
// backslashes (config-file strings treat backslash as an escape).
fn escape_single_quotes_ascii(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for c in src.chars() {
        if c == '\'' || c == '\\' {
            out.push(c);
        }
        out.push(c);
    }
    out
}

// replace_auto_config_value (guc.c:4537): remove any existing entry (or
// entries — external tools may add duplicates) for "name", then, unless
// value is None (a deletion), append a fresh entry at the tail.
fn replace_auto_config_value(list: &mut Vec<ConfigVariable>, name: &str, value: Option<&str>) {
    list.retain(|item| match &item.name {
        Some(item_name) => guc_name_compare(item_name, name) != Ordering::Equal,
        None => true,
    });
    let Some(value) = value else {
        return;
    };
    list.push(ConfigVariable::setting(
        name.to_string(),
        value.to_string(),
        std::path::PathBuf::new(),
        0,
    ));
}

// write_auto_conf_file's buffer (guc.c:4469): warning header plus one
// name = 'value' line per entry.
fn render_auto_conf_file(list: &[ConfigVariable]) -> String {
    let mut buf = String::new();
    buf.push_str("# Do not edit this file manually!\n");
    buf.push_str("# It will be overwritten by the ALTER SYSTEM command.\n");
    for item in list {
        let (Some(name), Some(value)) = (&item.name, &item.value) else {
            continue;
        };
        buf.push_str(name);
        buf.push_str(" = '");
        buf.push_str(&escape_single_quotes_ascii(value));
        buf.push_str("'\n");
    }
    buf
}

fn file_error(msg: String, e: &std::io::Error) -> PgError {
    let mut b = ereport(ERROR);
    if let Some(errno) = e.raw_os_error() {
        b = b.with_saved_errno(errno).errcode_for_file_access();
    }
    b.errmsg(msg).into_error()
}

// The flag/context checks and value validation from AlterSystemSetConfigFile
// (guc.c:4676-4744), run under one store borrow.
fn validate_auto_config_value(name: &str, value: Option<&str>) -> PgResult<()> {
    let found = guc::store::with_store(|reg| -> PgResult<bool> {
        let Some(record) = reg.find_option(name) else {
            return Ok(false);
        };
        let gen = record.gen();
        if gen.context == PGC_INTERNAL
            || gen.flags & GUC_DISALLOW_IN_FILE != 0
            || gen.flags & GUC_DISALLOW_IN_AUTO_FILE != 0
        {
            return Err(ereport(ERROR)
                .errcode(ERRCODE_CANT_CHANGE_RUNTIME_PARAM)
                .errmsg(format!("parameter \"{name}\" cannot be changed"))
                .into_error()
                .into());
        }
        if let Some(value) = value {
            // C wraps a false return in "invalid value for parameter"; the
            // ported parse_and_validate_value already errors in that form.
            let _ = guc::parse_and_validate_value(record, value, PGC_S_FILE)?;
        }
        Ok(true)
    })
    .expect("GUC store not initialized")?;

    if !found {
        // Unknown variable: check we'd be allowed to create it, except for a
        // RESET of an unknown custom GUC (reserved-prefix settings must stay
        // removable).
        if value.is_some() || !guc::valid_custom_variable_name(name) {
            guc::assignable_custom_variable_name(name, false)?;
        }
    }

    // The config-file grammar has no embedded newline in string literals.
    if value.is_some_and(|v| v.contains('\n')) {
        return Err(ereport(ERROR)
            .errcode(ERRCODE_INVALID_PARAMETER_VALUE)
            .errmsg("parameter value for ALTER SYSTEM must not contain a newline")
            .into_error()
            .into());
    }
    Ok(())
}

// AlterSystemSetConfigFile (guc.c:4607). On error the original
// postgresql.auto.conf is left intact; AutoFileLock serializes updates and is
// released by the abort path's LWLockReleaseAll on error, like C.
pub fn AlterSystemSetConfigFile(stmt: &AlterSystemStmt<'_>) -> PgResult<()> {
    let setstmt = stmt.setstmt;
    let name = setstmt.name.unwrap_or("");

    if !guc_tables::vars::AllowAlterSystem.read() {
        return Err(ereport(ERROR)
            .errcode(ERRCODE_FEATURE_NOT_SUPPORTED)
            .errmsg("ALTER SYSTEM is not allowed in this environment")
            .into_error()
            .into());
    }

    let mut resetall = false;
    let value: Option<String> = match setstmt.kind {
        VariableSetKind::VAR_SET_VALUE => ExtractSetVariableArgs(setstmt)?,
        VariableSetKind::VAR_SET_DEFAULT | VariableSetKind::VAR_RESET => None,
        VariableSetKind::VAR_RESET_ALL => {
            resetall = true;
            None
        }
        other => {
            return Err(ereport(ERROR)
                .errmsg_internal(format!(
                    "unrecognized alter system stmt type: {}",
                    other as i32
                ))
                .into_error()
                .into())
        }
    };

    if !superuser::superuser()? {
        if resetall {
            return Err(ereport(ERROR)
                .errcode(ERRCODE_INSUFFICIENT_PRIVILEGE)
                .errmsg("permission denied to perform ALTER SYSTEM RESET ALL")
                .into_error()
                .into());
        }
        let aclresult = aclchk_seams::pg_parameter_aclcheck::call(
            name,
            miscinit::GetUserId(),
            ACL_ALTER_SYSTEM,
        )?;
        if aclresult != ACLCHECK_OK {
            return Err(ereport(ERROR)
                .errcode(ERRCODE_INSUFFICIENT_PRIVILEGE)
                .errmsg(format!("permission denied to set parameter \"{name}\""))
                .into_error()
                .into());
        }
    }

    if !resetall {
        validate_auto_config_value(name, value.as_deref())?;
    }

    // Both files are always in the data directory (the backend's cwd), so
    // simple relative paths work.
    let tmp_file_name = format!("{PG_AUTOCONF_FILENAME}.tmp");

    lwlock::LWLockAcquire(
        lwlock::main_lock(AUTO_FILE_LOCK),
        lwlock::LW_EXCLUSIVE,
        init_small::globals::MyProcNumber(),
    )?;

    let mut head: Vec<ConfigVariable> = Vec::new();
    if !resetall {
        if let Some(contents) = read_autoconf_via_fd()? {
            if !ParseConfigFp(
                &contents,
                std::path::Path::new(PG_AUTOCONF_FILENAME),
                CONF_FILE_START_DEPTH,
                LOG,
                &mut head,
            )? {
                return Err(ereport(ERROR)
                    .errcode(ERRCODE_CONFIG_FILE_ERROR)
                    .errmsg(format!(
                        "could not parse contents of file \"{PG_AUTOCONF_FILENAME}\""
                    ))
                    .into_error()
                    .into());
            }
        }
        replace_auto_config_value(&mut head, name, value.as_deref());
    }

    // C: InvokeObjectPostAlterHookArgStr — the object_access_hook surface is
    // absent by design in this port.

    // Crash safety: write + fsync a temp file, then atomically rename it into
    // place. A leftover temp file from a previous crash is truncated/reused.
    let raw = fd::BasicOpenFile(&tmp_file_name, libc::O_CREAT | libc::O_RDWR | libc::O_TRUNC)?;
    if raw < 0 {
        return Err(file_error(
            format!("could not open file \"{tmp_file_name}\": %m"),
            &std::io::Error::last_os_error(),
        )
        .into());
    }
    let content = render_auto_conf_file(&head);
    if let Err(e) = write_and_sync_auto_conf_tmp(raw, content.as_bytes(), &tmp_file_name) {
        let _ = fd::pg_unlink(&tmp_file_name);
        return Err(e);
    }
    if let Err(e) = fd::durable_rename(&tmp_file_name, PG_AUTOCONF_FILENAME, ERROR) {
        let _ = fd::pg_unlink(&tmp_file_name);
        return Err(e);
    }

    lwlock::LWLockRelease(lwlock::main_lock(AUTO_FILE_LOCK))?;
    Ok(())
}

// write_auto_conf_file's IO tail (guc.c:4495-4509): write the rendered
// buffer, fsync "before considering the write to be successful", and close
// before the caller renames (PG_CATCH parity: the caller unlinks on error).
//
// DST P4 dataplane arm: the whole sequence runs through the Vfs data plane —
// BasicOpenFile minted `raw` via vfs::open, the writes are fd::pg_pwrite,
// the fsync is fd::pg_fsync (the call C makes here — enableFsync-gated,
// EINTR-retried, wal_sync_method-aware, unlike the std sync_all it
// replaces), the close is fd::pg_close — so under `--cfg pgrust_sim` every
// step lands in SimVfs and P4 fault plans can gate/crash each op
// (PWriteV / Fsync / Close on the temp file, then fd's durable_rename
// composite). Off-sim the syscalls are pwrite(2)/fsync(2)/close(2) — the
// same count the std::fs::File data plane issued on this cold DDL path.
fn write_and_sync_auto_conf_tmp(raw: i32, content: &[u8], tmp_file_name: &str) -> PgResult<()> {
    let result = (|| -> PgResult<()> {
        let mut off: usize = 0;
        while off < content.len() {
            let n = fd::pg_pwrite(raw, &content[off..], off as i64);
            if n < 0 {
                let en = fd::get_errno();
                if en == libc::EINTR {
                    continue;
                }
                return Err(file_error(
                    format!("could not write to file \"{tmp_file_name}\": %m"),
                    &std::io::Error::from_raw_os_error(en),
                )
                .into());
            }
            if n == 0 {
                // C parity (guc.c:4497): a write that makes no progress and
                // sets no errno is assumed to be out of disk space.
                return Err(file_error(
                    format!("could not write to file \"{tmp_file_name}\": %m"),
                    &std::io::Error::from_raw_os_error(libc::ENOSPC),
                )
                .into());
            }
            off += n as usize;
        }
        if fd::pg_fsync(raw) != 0 {
            return Err(file_error(
                format!("could not fsync file \"{tmp_file_name}\": %m"),
                &std::io::Error::from_raw_os_error(fd::get_errno()),
            )
            .into());
        }
        Ok(())
    })();
    // Close before renaming, error or not (PG_CATCH parity); the result is
    // ignored exactly as the old std File drop ignored it.
    let _ = fd::pg_close(raw);
    result
}

// postgresql.auto.conf read via the fd-crate front (DST P1 inc-4): transient
// fd + fstat-sized pg_pread. Ok(None) = ENOENT (fresh cluster). Errno-shaped
// failures become the C "could not open file" report here; a PgError from
// OpenTransientFile itself (e.g. desc-table exhaustion) propagates unchanged.
fn read_autoconf_via_fd() -> PgResult<Option<Vec<u8>>> {
    let io_err = |en: i32| {
        file_error(
            format!("could not open file \"{PG_AUTOCONF_FILENAME}\": %m"),
            &std::io::Error::from_raw_os_error(en),
        )
    };
    let fdnum = fd::OpenTransientFile(PG_AUTOCONF_FILENAME, libc::O_RDONLY)?;
    if fdnum < 0 {
        let en = fd::get_errno();
        if en == libc::ENOENT {
            return Ok(None);
        }
        return Err(io_err(en).into());
    }
    let mut fi = fd::FileInfo::zeroed();
    if fd::pg_fstat(fdnum, &mut fi) != 0 {
        let en = fd::get_errno();
        fd::CloseTransientFile(fdnum);
        return Err(io_err(en).into());
    }
    let mut contents = vec![0u8; fi.size.max(0) as usize];
    let mut r = 0usize;
    while r < contents.len() {
        let n = fd::pg_pread(fdnum, &mut contents[r..], r as i64);
        if n == 0 {
            contents.truncate(r);
            break;
        }
        if n < 0 {
            let en = fd::get_errno();
            if en == libc::EINTR {
                continue;
            }
            fd::CloseTransientFile(fdnum);
            return Err(io_err(en).into());
        }
        r += n as usize;
    }
    fd::CloseTransientFile(fdnum);
    Ok(Some(contents))
}

// DST P4 dataplane arm (site: the postgresql.auto.conf temp-file rewrite).
#[cfg(all(test, pgrust_sim))]
mod sim_dataplane_tests {
    use super::write_and_sync_auto_conf_tmp;

    /// The write/fsync/close tail must land in the SAME provider that
    /// minted the fd (SimVfs under `--cfg pgrust_sim`): the bytes read back
    /// through the vfs, the fsync promoted them into the durable image
    /// (what a P4 crash plan rolls back to), the fd is closed sim-side, and
    /// the real filesystem never saw the file. RED before the routing:
    /// BasicOpenFile minted a sim fd but the data plane was std::fs::File —
    /// kernel write(2)/fsync(2)/close(2) on an fd >= SIM_FD_BASE (EBADF +
    /// std's IO-safety abort on the File drop).
    #[test]
    fn sim_auto_conf_tmp_write_lands_in_simvfs() {
        // pg_fsync consults wal_sync_method (macOS writethrough dispatch);
        // give the slot a default backing, as fd's own tests do.
        static WAL_SYNC_METHOD: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(0);
        guc_tables::vars::wal_sync_method.install_if_absent(guc_tables::GucVarAccessors {
            get: || WAL_SYNC_METHOD.load(std::sync::atomic::Ordering::Relaxed),
            set: |v| WAL_SYNC_METHOD.store(v, std::sync::atomic::Ordering::Relaxed),
        });

        let name = "pgrust-dataplane-test.auto.conf.tmp";
        let content: &[u8] = b"# Do not edit this file manually!\nwork_mem = '64MB'\n";
        let raw = fd::BasicOpenFile(name, libc::O_CREAT | libc::O_RDWR | libc::O_TRUNC).unwrap();
        assert!(raw >= 0, "BasicOpenFile: errno {}", fd::get_errno());
        write_and_sync_auto_conf_tmp(raw, content, name).unwrap();

        // The fd is closed (sim-side): fstat on it is EBADF, not a leak.
        let mut fi = fd::FileInfo::zeroed();
        assert_ne!(
            fd::pg_fstat(raw, &mut fi),
            0,
            "tmp fd still open after helper"
        );
        assert_eq!(fd::get_errno(), libc::EBADF);

        // The bytes are visible through the vfs read plane.
        let rd = fd::BasicOpenFile(name, libc::O_RDONLY).unwrap();
        assert!(rd >= 0, "reopen: errno {}", fd::get_errno());
        let mut back = vec![0u8; content.len() + 8];
        let n = fd::pg_pread(rd, &mut back, 0);
        assert_eq!(n as usize, content.len());
        assert_eq!(&back[..content.len()], content);
        let _ = fd::pg_close(rd);

        // The fsync step promoted the volatile image to durable.
        let dump = vfs::ACTIVE.image_dump();
        let entry = dump
            .iter()
            .find(|(p, _)| p.ends_with(name))
            .expect("tmp file present in the sim namespace");
        let (volatile, durable) = entry.1.as_ref().expect("regular file");
        assert_eq!(volatile.as_slice(), content);
        assert_eq!(
            durable.as_slice(),
            content,
            "fsync did not promote the durable image"
        );

        // The real filesystem never saw it.
        assert!(
            std::fs::metadata(name).is_err(),
            "temp file leaked to the real fs"
        );
    }
}
