// GENERATED from C daitch_mokotoff.h (itself generated by
// daitch_mokotoff_header.pl); regenerate with the same script, do not hand-edit.

pub type DmCode = [u8; 3];
pub type DmCodes = [DmCode; 3];

pub struct DmLetter {
    pub letter: u8,
    pub letters: &'static [DmLetter],
    pub codes: &'static [DmCodes],
}

static CODES_0_1_X: [DmCodes; 1] = [[*b"0\0\0", *b"1\0\0", *b"X\0\0"]];
static CODES_0_7_X: [DmCodes; 1] = [[*b"0\0\0", *b"7\0\0", *b"X\0\0"]];
static CODES_0_X_X: [DmCodes; 1] = [[*b"0\0\0", *b"X\0\0", *b"X\0\0"]];
static CODES_1_1_X: [DmCodes; 1] = [[*b"1\0\0", *b"1\0\0", *b"X\0\0"]];
static CODES_1_X_X: [DmCodes; 1] = [[*b"1\0\0", *b"X\0\0", *b"X\0\0"]];
static CODES_1_X_X_OR_4_4_4: [DmCodes; 2] = [
    [*b"1\0\0", *b"X\0\0", *b"X\0\0"],
    [*b"4\0\0", *b"4\0\0", *b"4\0\0"],
];
static CODES_2_43_43: [DmCodes; 1] = [[*b"2\0\0", *b"43\0", *b"43\0"]];
static CODES_2_4_4: [DmCodes; 1] = [[*b"2\0\0", *b"4\0\0", *b"4\0\0"]];
static CODES_3_3_3: [DmCodes; 1] = [[*b"3\0\0", *b"3\0\0", *b"3\0\0"]];
static CODES_3_3_3_OR_4_4_4: [DmCodes; 2] = [
    [*b"3\0\0", *b"3\0\0", *b"3\0\0"],
    [*b"4\0\0", *b"4\0\0", *b"4\0\0"],
];
static CODES_4_4_4: [DmCodes; 1] = [[*b"4\0\0", *b"4\0\0", *b"4\0\0"]];
static CODES_5_54_54: [DmCodes; 1] = [[*b"5\0\0", *b"54\0", *b"54\0"]];
static CODES_5_5_5: [DmCodes; 1] = [[*b"5\0\0", *b"5\0\0", *b"5\0\0"]];
static CODES_5_5_5_OR_45_45_45: [DmCodes; 2] = [
    [*b"5\0\0", *b"5\0\0", *b"5\0\0"],
    [*b"45\0", *b"45\0", *b"45\0"],
];
static CODES_5_5_5_OR_4_4_4: [DmCodes; 2] = [
    [*b"5\0\0", *b"5\0\0", *b"5\0\0"],
    [*b"4\0\0", *b"4\0\0", *b"4\0\0"],
];
static CODES_5_5_X: [DmCodes; 1] = [[*b"5\0\0", *b"5\0\0", *b"X\0\0"]];
static CODES_66_66_66: [DmCodes; 1] = [[*b"66\0", *b"66\0", *b"66\0"]];
static CODES_6_6_6: [DmCodes; 1] = [[*b"6\0\0", *b"6\0\0", *b"6\0\0"]];
static CODES_7_7_7: [DmCodes; 1] = [[*b"7\0\0", *b"7\0\0", *b"7\0\0"]];
static CODES_8_8_8: [DmCodes; 1] = [[*b"8\0\0", *b"8\0\0", *b"8\0\0"]];
static CODES_94_94_94_OR_4_4_4: [DmCodes; 2] = [
    [*b"94\0", *b"94\0", *b"94\0"],
    [*b"4\0\0", *b"4\0\0", *b"4\0\0"],
];
static CODES_9_9_9: [DmCodes; 1] = [[*b"9\0\0", *b"9\0\0", *b"9\0\0"]];
static CODES_X_X_6_OR_X_X_X: [DmCodes; 2] = [
    [*b"X\0\0", *b"X\0\0", *b"6\0\0"],
    [*b"X\0\0", *b"X\0\0", *b"X\0\0"],
];

pub static LETTER_A: [DmLetter; 4] = [
    DmLetter {
        letter: b'I',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'J',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'U',
        letters: &[],
        codes: &CODES_0_7_X,
    },
    DmLetter {
        letter: b'Y',
        letters: &[],
        codes: &CODES_0_1_X,
    },
];
pub static LETTER_CH: [DmLetter; 1] = [DmLetter {
    letter: b'S',
    letters: &[],
    codes: &CODES_5_54_54,
}];
pub static LETTER_CS: [DmLetter; 1] = [DmLetter {
    letter: b'Z',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_CZ: [DmLetter; 1] = [DmLetter {
    letter: b'S',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_C: [DmLetter; 4] = [
    DmLetter {
        letter: b'H',
        letters: &LETTER_CH,
        codes: &CODES_5_5_5_OR_4_4_4,
    },
    DmLetter {
        letter: b'K',
        letters: &[],
        codes: &CODES_5_5_5_OR_45_45_45,
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_CS,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &LETTER_CZ,
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_DR: [DmLetter; 2] = [
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_DS: [DmLetter; 2] = [
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_DZ: [DmLetter; 2] = [
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_D: [DmLetter; 4] = [
    DmLetter {
        letter: b'R',
        letters: &LETTER_DR,
        codes: &[],
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_DS,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'T',
        letters: &[],
        codes: &CODES_3_3_3,
    },
    DmLetter {
        letter: b'Z',
        letters: &LETTER_DZ,
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_E: [DmLetter; 4] = [
    DmLetter {
        letter: b'I',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'J',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'U',
        letters: &[],
        codes: &CODES_1_1_X,
    },
    DmLetter {
        letter: b'Y',
        letters: &[],
        codes: &CODES_0_1_X,
    },
];
pub static LETTER_F: [DmLetter; 1] = [DmLetter {
    letter: b'B',
    letters: &[],
    codes: &CODES_7_7_7,
}];
pub static LETTER_I: [DmLetter; 4] = [
    DmLetter {
        letter: b'A',
        letters: &[],
        codes: &CODES_1_X_X,
    },
    DmLetter {
        letter: b'E',
        letters: &[],
        codes: &CODES_1_X_X,
    },
    DmLetter {
        letter: b'O',
        letters: &[],
        codes: &CODES_1_X_X,
    },
    DmLetter {
        letter: b'U',
        letters: &[],
        codes: &CODES_1_X_X,
    },
];
pub static LETTER_K: [DmLetter; 2] = [
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_5_5_5,
    },
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_5_54_54,
    },
];
pub static LETTER_M: [DmLetter; 1] = [DmLetter {
    letter: b'N',
    letters: &[],
    codes: &CODES_66_66_66,
}];
pub static LETTER_N: [DmLetter; 1] = [DmLetter {
    letter: b'M',
    letters: &[],
    codes: &CODES_66_66_66,
}];
pub static LETTER_O: [DmLetter; 3] = [
    DmLetter {
        letter: b'I',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'J',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'Y',
        letters: &[],
        codes: &CODES_0_1_X,
    },
];
pub static LETTER_P: [DmLetter; 2] = [
    DmLetter {
        letter: b'F',
        letters: &[],
        codes: &CODES_7_7_7,
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_7_7_7,
    },
];
pub static LETTER_R: [DmLetter; 2] = [
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_94_94_94_OR_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_94_94_94_OR_4_4_4,
    },
];
pub static LETTER_SCHTC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_SCHTSC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_SCHTS: [DmLetter; 2] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_SCHTSC,
        codes: &[],
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_2_4_4,
    },
];
pub static LETTER_SCHT: [DmLetter; 2] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_SCHTC,
        codes: &[],
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_SCHTS,
        codes: &[],
    },
];
pub static LETTER_SCH: [DmLetter; 2] = [
    DmLetter {
        letter: b'D',
        letters: &[],
        codes: &CODES_2_43_43,
    },
    DmLetter {
        letter: b'T',
        letters: &LETTER_SCHT,
        codes: &CODES_2_43_43,
    },
];
pub static LETTER_SC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &LETTER_SCH,
    codes: &CODES_4_4_4,
}];
pub static LETTER_SHC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_SHTC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_SHTS: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_SHT: [DmLetter; 2] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_SHTC,
        codes: &[],
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_SHTS,
        codes: &[],
    },
];
pub static LETTER_SH: [DmLetter; 3] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_SHC,
        codes: &[],
    },
    DmLetter {
        letter: b'D',
        letters: &[],
        codes: &CODES_2_43_43,
    },
    DmLetter {
        letter: b'T',
        letters: &LETTER_SHT,
        codes: &CODES_2_43_43,
    },
];
pub static LETTER_STC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_STR: [DmLetter; 2] = [
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_2_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_2_4_4,
    },
];
pub static LETTER_STSC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_STS: [DmLetter; 2] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_STSC,
        codes: &[],
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_2_4_4,
    },
];
pub static LETTER_ST: [DmLetter; 3] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_STC,
        codes: &[],
    },
    DmLetter {
        letter: b'R',
        letters: &LETTER_STR,
        codes: &[],
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_STS,
        codes: &[],
    },
];
pub static LETTER_SZC: [DmLetter; 2] = [
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_2_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_2_4_4,
    },
];
pub static LETTER_SZ: [DmLetter; 3] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_SZC,
        codes: &[],
    },
    DmLetter {
        letter: b'D',
        letters: &[],
        codes: &CODES_2_43_43,
    },
    DmLetter {
        letter: b'T',
        letters: &[],
        codes: &CODES_2_43_43,
    },
];
pub static LETTER_S: [DmLetter; 5] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_SC,
        codes: &CODES_2_4_4,
    },
    DmLetter {
        letter: b'D',
        letters: &[],
        codes: &CODES_2_43_43,
    },
    DmLetter {
        letter: b'H',
        letters: &LETTER_SH,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'T',
        letters: &LETTER_ST,
        codes: &CODES_2_43_43,
    },
    DmLetter {
        letter: b'Z',
        letters: &LETTER_SZ,
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_TC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_TR: [DmLetter; 2] = [
    DmLetter {
        letter: b'S',
        letters: &[],
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_TSC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_TS: [DmLetter; 3] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_TSC,
        codes: &[],
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_TTC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_TTSC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_TTS: [DmLetter; 2] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_TTSC,
        codes: &[],
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_TT: [DmLetter; 3] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_TTC,
        codes: &[],
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_TTS,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'Z',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_TZ: [DmLetter; 1] = [DmLetter {
    letter: b'S',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_T: [DmLetter; 6] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_TC,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_3_3_3,
    },
    DmLetter {
        letter: b'R',
        letters: &LETTER_TR,
        codes: &[],
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_TS,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'T',
        letters: &LETTER_TT,
        codes: &[],
    },
    DmLetter {
        letter: b'Z',
        letters: &LETTER_TZ,
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_U: [DmLetter; 4] = [
    DmLetter {
        letter: b'E',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'I',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'J',
        letters: &[],
        codes: &CODES_0_1_X,
    },
    DmLetter {
        letter: b'Y',
        letters: &[],
        codes: &CODES_0_1_X,
    },
];
pub static LETTER_ZDZ: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_ZD: [DmLetter; 1] = [DmLetter {
    letter: b'Z',
    letters: &LETTER_ZDZ,
    codes: &CODES_2_4_4,
}];
pub static LETTER_ZHDZ: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_2_4_4,
}];
pub static LETTER_ZHD: [DmLetter; 1] = [DmLetter {
    letter: b'Z',
    letters: &LETTER_ZHDZ,
    codes: &[],
}];
pub static LETTER_ZH: [DmLetter; 1] = [DmLetter {
    letter: b'D',
    letters: &LETTER_ZHD,
    codes: &CODES_2_43_43,
}];
pub static LETTER_ZSC: [DmLetter; 1] = [DmLetter {
    letter: b'H',
    letters: &[],
    codes: &CODES_4_4_4,
}];
pub static LETTER_ZS: [DmLetter; 2] = [
    DmLetter {
        letter: b'C',
        letters: &LETTER_ZSC,
        codes: &[],
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_Z: [DmLetter; 3] = [
    DmLetter {
        letter: b'D',
        letters: &LETTER_ZD,
        codes: &CODES_2_43_43,
    },
    DmLetter {
        letter: b'H',
        letters: &LETTER_ZH,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_ZS,
        codes: &CODES_4_4_4,
    },
];
pub static LETTER_ROOT: [DmLetter; 29] = [
    DmLetter {
        letter: b'A',
        letters: &LETTER_A,
        codes: &CODES_0_X_X,
    },
    DmLetter {
        letter: b'B',
        letters: &[],
        codes: &CODES_7_7_7,
    },
    DmLetter {
        letter: b'C',
        letters: &LETTER_C,
        codes: &CODES_5_5_5_OR_4_4_4,
    },
    DmLetter {
        letter: b'D',
        letters: &LETTER_D,
        codes: &CODES_3_3_3,
    },
    DmLetter {
        letter: b'E',
        letters: &LETTER_E,
        codes: &CODES_0_X_X,
    },
    DmLetter {
        letter: b'F',
        letters: &LETTER_F,
        codes: &CODES_7_7_7,
    },
    DmLetter {
        letter: b'G',
        letters: &[],
        codes: &CODES_5_5_5,
    },
    DmLetter {
        letter: b'H',
        letters: &[],
        codes: &CODES_5_5_X,
    },
    DmLetter {
        letter: b'I',
        letters: &LETTER_I,
        codes: &CODES_0_X_X,
    },
    DmLetter {
        letter: b'J',
        letters: &[],
        codes: &CODES_1_X_X_OR_4_4_4,
    },
    DmLetter {
        letter: b'K',
        letters: &LETTER_K,
        codes: &CODES_5_5_5,
    },
    DmLetter {
        letter: b'L',
        letters: &[],
        codes: &CODES_8_8_8,
    },
    DmLetter {
        letter: b'M',
        letters: &LETTER_M,
        codes: &CODES_6_6_6,
    },
    DmLetter {
        letter: b'N',
        letters: &LETTER_N,
        codes: &CODES_6_6_6,
    },
    DmLetter {
        letter: b'O',
        letters: &LETTER_O,
        codes: &CODES_0_X_X,
    },
    DmLetter {
        letter: b'P',
        letters: &LETTER_P,
        codes: &CODES_7_7_7,
    },
    DmLetter {
        letter: b'Q',
        letters: &[],
        codes: &CODES_5_5_5,
    },
    DmLetter {
        letter: b'R',
        letters: &LETTER_R,
        codes: &CODES_9_9_9,
    },
    DmLetter {
        letter: b'S',
        letters: &LETTER_S,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'T',
        letters: &LETTER_T,
        codes: &CODES_3_3_3,
    },
    DmLetter {
        letter: b'U',
        letters: &LETTER_U,
        codes: &CODES_0_X_X,
    },
    DmLetter {
        letter: b'V',
        letters: &[],
        codes: &CODES_7_7_7,
    },
    DmLetter {
        letter: b'W',
        letters: &[],
        codes: &CODES_7_7_7,
    },
    DmLetter {
        letter: b'X',
        letters: &[],
        codes: &CODES_5_54_54,
    },
    DmLetter {
        letter: b'Y',
        letters: &[],
        codes: &CODES_1_X_X,
    },
    DmLetter {
        letter: b'Z',
        letters: &LETTER_Z,
        codes: &CODES_4_4_4,
    },
    DmLetter {
        letter: b'a',
        letters: &[],
        codes: &CODES_X_X_6_OR_X_X_X,
    },
    DmLetter {
        letter: b'e',
        letters: &[],
        codes: &CODES_X_X_6_OR_X_X_X,
    },
    DmLetter {
        letter: b't',
        letters: &[],
        codes: &CODES_3_3_3_OR_4_4_4,
    },
];
