// Vectors generated by running the vendored src/common/wchar.c (see data/).
mod c_vectors {
    include!("data/c_vectors.rs");
}
use c_vectors::*;
use wchar::*;

struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf29ce484222325)
    }
    fn h32(&mut self, v: u32) {
        for i in 0..4 {
            self.0 ^= ((v >> (8 * i)) & 0xff) as u64;
            self.0 = self.0.wrapping_mul(0x100000001b3);
        }
    }
}

#[test]
fn max_length_matches_c() {
    for e in 0..42 {
        assert_eq!(pg_encoding_max_length(e), MAXMBLEN[e as usize], "enc {e}");
    }
}

#[test]
fn mblen_tables_match_c() {
    for e in 0..42i32 {
        for b in 0..256usize {
            let buf41 = [b as u8, 0x41, 0x42, 0x43, 0];
            let buf30 = [b as u8, 0x30, 0x42, 0x43, 0];
            assert_eq!(
                pg_encoding_mblen(e, &buf41),
                MBLEN_B1_41[e as usize][b] as i32,
                "enc {e} b {b}"
            );
            assert_eq!(
                pg_encoding_mblen(e, &buf30),
                MBLEN_B1_30[e as usize][b] as i32,
                "enc {e} b {b}"
            );
            let bufz = [b as u8, 0x31, 0, 0x33, 0];
            assert_eq!(
                pg_encoding_mblen_bounded(e, &bufz),
                MBLEN_BOUNDED[e as usize][b] as i32,
                "enc {e} b {b}"
            );
        }
    }
}

#[test]
fn dsplen_tables_match_c() {
    for e in 0..42i32 {
        for b in 0..256usize {
            let buf = [b as u8, 0xa4, 0xb9, 0x8e, 0];
            assert_eq!(
                pg_encoding_dsplen(e, &buf),
                DSPLEN[e as usize][b] as i32,
                "enc {e} b {b}"
            );
        }
    }
}

#[test]
fn verifychar_pairs_match_c() {
    for e in 0..42i32 {
        let mut f = Fnv::new();
        for b0 in 0..256usize {
            for b1 in 0..256usize {
                let buf = [b0 as u8, b1 as u8];
                f.h32(pg_encoding_verifymbchar(e, &buf) as u32);
                f.h32(pg_encoding_verifymbchar(e, &buf[..1]) as u32);
            }
        }
        assert_eq!(f.0, VERIFYCHAR2_HASH[e as usize], "enc {e}");
    }
}

const B2S: [u8; 16] = [
    0x00, 0x20, 0x2f, 0x30, 0x39, 0x40, 0x7e, 0x7f, 0x80, 0x8f, 0x9f, 0xa0, 0xa1, 0xbf, 0xc0, 0xfe,
];

#[test]
fn verify_triples_match_c() {
    for e in 0..42i32 {
        let mut f = Fnv::new();
        for b0 in 0..256usize {
            for b1 in 0..256usize {
                for &b2 in &B2S {
                    let buf = [b0 as u8, b1 as u8, b2];
                    f.h32(pg_encoding_verifymbchar(e, &buf) as u32);
                    f.h32(pg_encoding_verifymbstr(e, &buf) as u32);
                }
            }
        }
        assert_eq!(f.0, VERIFY3_HASH[e as usize], "enc {e}");
    }
}

#[test]
fn verify_quads_match_c() {
    const B0S4: [u8; 12] = [
        0x8e, 0x8f, 0x9a, 0x9c, 0xe0, 0xed, 0xf0, 0xf1, 0xf4, 0xf5, 0x81, 0xfe,
    ];
    for e in 0..42i32 {
        let mut f = Fnv::new();
        for &b0 in &B0S4 {
            for b1 in 0..256usize {
                for &b2 in &B2S {
                    for b3 in (0..256usize).step_by(17) {
                        let buf = [b0, b1 as u8, b2, b3 as u8];
                        f.h32(pg_encoding_verifymbchar(e, &buf) as u32);
                        f.h32(pg_encoding_verifymbstr(e, &buf) as u32);
                    }
                }
            }
        }
        assert_eq!(f.0, VERIFY4_HASH[e as usize], "enc {e}");
    }
}

#[test]
fn utf8_verify_3byte_exhaustive_matches_c() {
    let mut f = Fnv::new();
    for b0 in 0..256usize {
        for b1 in 0..256usize {
            for b2 in 0..256usize {
                let buf = [b0 as u8, b1 as u8, b2 as u8];
                f.h32(pg_encoding_verifymbchar(PG_UTF8, &buf) as u32);
                f.h32(pg_encoding_verifymbstr(PG_UTF8, &buf) as u32);
            }
        }
    }
    assert_eq!(f.0, UTF8_VERIFY3_EXHAUSTIVE_HASH);
}

#[test]
fn utf8_codepoint_walk_matches_c() {
    let mut f = Fnv::new();
    for cp in 1u32..=0x10ffff {
        let mut buf = [0u8; 5];
        unicode_to_utf8(cp, &mut buf);
        f.h32(pg_encoding_dsplen(PG_UTF8, &buf) as u32);
        f.h32(utf8_to_unicode(&buf));
        f.h32(pg_utf_mblen(&buf) as u32);
        f.h32(pg_utf8_islegal(&buf, pg_utf_mblen(&buf)) as u32);
    }
    assert_eq!(f.0, UTF8_CODEPOINT_HASH);
}

#[test]
fn verifystr_corpora_match_c() {
    assert_eq!(CORPORA.len(), VERIFYSTR_EXPECT.len());
    for (i, corpus) in CORPORA.iter().enumerate() {
        for e in 0..42i32 {
            assert_eq!(
                pg_encoding_verifymbstr(e, corpus),
                VERIFYSTR_EXPECT[i][e as usize],
                "corpus {i} enc {e}"
            );
        }
    }
}

#[test]
fn mb2wchar_matches_c() {
    for e in 0..=PG_ENCODING_BE_LAST {
        let conv = pg_wchar_table[e as usize].mb2wchar_with_len.unwrap();
        let mut f = Fnv::new();
        let mut to = vec![0u32; 4097];
        for corpus in CORPORA {
            let cnt = conv(corpus, &mut to);
            f.h32(cnt as u32);
            for k in 0..=cnt as usize {
                f.h32(to[k]);
            }
        }
        assert_eq!(f.0, MB2WCHAR_HASH[e as usize], "enc {e}");
    }
}

#[test]
fn wchar2mb_matches_c() {
    let mut prng: u64 = 0x0123456789abcdef;
    let mut next64 = move || {
        prng = prng
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        prng
    };
    let mut wsrc = [[0u32; 129]; 64];
    for row in wsrc.iter_mut() {
        for k in 0..128 {
            let r = next64();
            let mut w = r as u32;
            match r % 4 {
                0 => w &= 0x7f,
                1 => w &= 0xffff,
                2 => w &= 0xffffff,
                _ => {}
            }
            row[k] = if w != 0 { w } else { 1 };
        }
        row[128] = 0;
    }
    for e in 0..=PG_ENCODING_BE_LAST {
        let conv = pg_wchar_table[e as usize].wchar2mb_with_len.unwrap();
        let mut f = Fnv::new();
        let mut to = [0u8; 4 * 128 + 1];
        for row in &wsrc {
            let cnt = conv(&row[..128], &mut to);
            f.h32(cnt as u32);
            for k in 0..=cnt as usize {
                f.h32(to[k] as u32);
            }
        }
        assert_eq!(f.0, WCHAR2MB_HASH[e as usize], "enc {e}");
    }
}

#[test]
fn set_invalid_matches_c() {
    let mut buf = [0u8; 2];
    pg_encoding_set_invalid(PG_UTF8, &mut buf);
    assert_eq!(buf, SET_INVALID_UTF8);
    pg_encoding_set_invalid(PG_EUC_JP, &mut buf);
    assert_eq!(buf, SET_INVALID_OTHER);
}

#[test]
fn or_incomplete_edge_cases() {
    assert_eq!(pg_encoding_mblen_or_incomplete(PG_UTF8, &[]), i32::MAX);
    assert_eq!(
        pg_encoding_mblen_or_incomplete(PG_GB18030, &[0x81]),
        i32::MAX
    );
    assert_eq!(
        pg_encoding_mblen_or_incomplete(PG_GB18030, &[0x81, 0x30]),
        4
    );
    assert_eq!(pg_encoding_mblen_or_incomplete(PG_GB18030, &[0x41]), 1);
    assert_eq!(pg_encoding_mblen_or_incomplete(PG_UTF8, &[0xf0]), 4);
}
