// Round-trip vectors extracted from C 18.3 regress expected/jsonpath.out.
pub static OK_VECTORS: &[(&str, &str)] = &[
    ("$", "$"),
    ("strict $", "strict $"),
    ("lax $", "$"),
    ("$.a", "$.\"a\""),
    ("$.a.v", "$.\"a\".\"v\""),
    ("$.a.*", "$.\"a\".*"),
    ("$.*[*]", "$.*[*]"),
    ("$.a[*]", "$.\"a\"[*]"),
    ("$.a[*][*]", "$.\"a\"[*][*]"),
    ("$[*]", "$[*]"),
    ("$[0]", "$[0]"),
    ("$[*][0]", "$[*][0]"),
    ("$[*].a", "$[*].\"a\""),
    ("$[*][0].a.b", "$[*][0].\"a\".\"b\""),
    ("$.a.**.b", "$.\"a\".**.\"b\""),
    ("$.a.**{2}.b", "$.\"a\".**{2}.\"b\""),
    ("$.a.**{2 to 2}.b", "$.\"a\".**{2}.\"b\""),
    ("$.a.**{2 to 5}.b", "$.\"a\".**{2 to 5}.\"b\""),
    ("$.a.**{0 to 5}.b", "$.\"a\".**{0 to 5}.\"b\""),
    ("$.a.**{5 to last}.b", "$.\"a\".**{5 to last}.\"b\""),
    ("$.a.**{last}.b", "$.\"a\".**{last}.\"b\""),
    ("$.a.**{last to 5}.b", "$.\"a\".**{last to 5}.\"b\""),
    ("$+1", "($ + 1)"),
    ("$-1", "($ - 1)"),
    ("$--+1", "($ - -1)"),
    ("$.a/+-1", "($.\"a\" / -1)"),
    ("1 * 2 + 4 % -3 != false", "(1 * 2 + 4 % -3 != false)"),
    (
        "\"\\b\\f\\r\\n\\t\\v\\\"\\'\\\\\"",
        "\"\\b\\f\\r\\n\\t\\u000b\\\"'\\\\\"",
    ),
    ("\"\\x50\\u0067\\u{53}\\u{051}\\u{00004C}\"", "\"PgSQL\""),
    (
        "$.foo\\x50\\u0067\\u{53}\\u{051}\\u{00004C}\\t\\\"bar",
        "$.\"fooPgSQL\\t\\\"bar\"",
    ),
    ("$.g ? ($.a == 1)", "$.\"g\"?($.\"a\" == 1)"),
    ("$.g ? (@ == 1)", "$.\"g\"?(@ == 1)"),
    ("$.g ? (@.a == 1)", "$.\"g\"?(@.\"a\" == 1)"),
    (
        "$.g ? (@.a == 1 || @.a == 4)",
        "$.\"g\"?(@.\"a\" == 1 || @.\"a\" == 4)",
    ),
    (
        "$.g ? (@.a == 1 && @.a == 4)",
        "$.\"g\"?(@.\"a\" == 1 && @.\"a\" == 4)",
    ),
    (
        "$.g ? (@.a == 1 || @.a == 4 && @.b == 7)",
        "$.\"g\"?(@.\"a\" == 1 || @.\"a\" == 4 && @.\"b\" == 7)",
    ),
    (
        "$.g ? (@.a == 1 || !(@.a == 4) && @.b == 7)",
        "$.\"g\"?(@.\"a\" == 1 || !(@.\"a\" == 4) && @.\"b\" == 7)",
    ),
    (
        "$.g ? (@.a == 1 || !(@.x >= 123 || @.a == 4) && @.b == 7)",
        "$.\"g\"?(@.\"a\" == 1 || !(@.\"x\" >= 123 || @.\"a\" == 4) && @.\"b\" == 7)",
    ),
    (
        "$.g ? (@.x >= @[*]?(@.a > \"abc\"))",
        "$.\"g\"?(@.\"x\" >= @[*]?(@.\"a\" > \"abc\"))",
    ),
    (
        "$.g ? ((@.x >= 123 || @.a == 4) is unknown)",
        "$.\"g\"?((@.\"x\" >= 123 || @.\"a\" == 4) is unknown)",
    ),
    ("$.g ? (exists (@.x))", "$.\"g\"?(exists (@.\"x\"))"),
    (
        "$.g ? (exists (@.x ? (@ == 14)))",
        "$.\"g\"?(exists (@.\"x\"?(@ == 14)))",
    ),
    (
        "$.g ? ((@.x >= 123 || @.a == 4) && exists (@.x ? (@ == 14)))",
        "$.\"g\"?((@.\"x\" >= 123 || @.\"a\" == 4) && exists (@.\"x\"?(@ == 14)))",
    ),
    (
        "$.g ? (+@.x >= +-(+@.a + 2))",
        "$.\"g\"?(+@.\"x\" >= +(-(+@.\"a\" + 2)))",
    ),
    ("$a", "$\"a\""),
    ("$a.b", "$\"a\".\"b\""),
    ("$a[*]", "$\"a\"[*]"),
    ("$.g ? (@.zip == $zip)", "$.\"g\"?(@.\"zip\" == $\"zip\")"),
    ("$.a[1,2, 3 to 16]", "$.\"a\"[1,2,3 to 16]"),
    (
        "$.a[$a + 1, ($b[*]) to -($[0] * 2)]",
        "$.\"a\"[$\"a\" + 1,$\"b\"[*] to -($[0] * 2)]",
    ),
    ("$.a[$.a.size() - 3]", "$.\"a\"[$.\"a\".size() - 3]"),
    ("\"last\"", "\"last\""),
    ("$.last", "$.\"last\""),
    ("$[last]", "$[last]"),
    ("$[$[0] ? (last > 0)]", "$[$[0]?(last > 0)]"),
    ("null.type()", "null.type()"),
    ("(1).type()", "(1).type()"),
    ("1.2.type()", "(1.2).type()"),
    ("\"aaa\".type()", "\"aaa\".type()"),
    ("true.type()", "true.type()"),
    (
        "$.double().floor().ceiling().abs()",
        "$.double().floor().ceiling().abs()",
    ),
    ("$.keyvalue().key", "$.keyvalue().\"key\""),
    ("$.datetime()", "$.datetime()"),
    (
        "$.datetime(\"datetime template\")",
        "$.datetime(\"datetime template\")",
    ),
    (
        "$.bigint().integer().number().decimal()",
        "$.bigint().integer().number().decimal()",
    ),
    ("$.boolean()", "$.boolean()"),
    ("$.date()", "$.date()"),
    ("$.decimal(4,2)", "$.decimal(4,2)"),
    ("$.string()", "$.string()"),
    ("$.time()", "$.time()"),
    ("$.time(6)", "$.time(6)"),
    ("$.time_tz()", "$.time_tz()"),
    ("$.time_tz(4)", "$.time_tz(4)"),
    ("$.timestamp()", "$.timestamp()"),
    ("$.timestamp(2)", "$.timestamp(2)"),
    ("$.timestamp_tz()", "$.timestamp_tz()"),
    ("$.timestamp_tz(0)", "$.timestamp_tz(0)"),
    ("$ ? (@ starts with \"abc\")", "$?(@ starts with \"abc\")"),
    ("$ ? (@ starts with $var)", "$?(@ starts with $\"var\")"),
    (
        "$ ? (@ like_regex \"pattern\")",
        "$?(@ like_regex \"pattern\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"\")",
        "$?(@ like_regex \"pattern\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"i\")",
        "$?(@ like_regex \"pattern\" flag \"i\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"is\")",
        "$?(@ like_regex \"pattern\" flag \"is\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"isim\")",
        "$?(@ like_regex \"pattern\" flag \"ism\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"q\")",
        "$?(@ like_regex \"pattern\" flag \"q\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"iq\")",
        "$?(@ like_regex \"pattern\" flag \"iq\")",
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"smixq\")",
        "$?(@ like_regex \"pattern\" flag \"ismxq\")",
    ),
    ("$ < 1", "($ < 1)"),
    (
        "($ < 1) || $.a.b <= $x",
        "($ < 1 || $.\"a\".\"b\" <= $\"x\")",
    ),
    ("($).a.b", "$.\"a\".\"b\""),
    ("($.a.b).c.d", "$.\"a\".\"b\".\"c\".\"d\""),
    (
        "($.a.b + -$.x.y).c.d",
        "($.\"a\".\"b\" + -$.\"x\".\"y\").\"c\".\"d\"",
    ),
    ("(-+$.a.b).c.d", "(-(+$.\"a\".\"b\")).\"c\".\"d\""),
    (
        "1 + ($.a.b + 2).c.d",
        "(1 + ($.\"a\".\"b\" + 2).\"c\".\"d\")",
    ),
    (
        "1 + ($.a.b > 2).c.d",
        "(1 + ($.\"a\".\"b\" > 2).\"c\".\"d\")",
    ),
    ("($)", "$"),
    ("(($))", "$"),
    (
        "((($ + 1)).a + ((2)).b ? ((((@ > 1)) || (exists(@.c)))))",
        "(($ + 1).\"a\" + (2).\"b\"?(@ > 1 || exists (@.\"c\")))",
    ),
    ("$ ? (@.a < 1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < -1)", "$?(@.\"a\" < -1)"),
    ("$ ? (@.a < +1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < .1)", "$?(@.\"a\" < 0.1)"),
    ("$ ? (@.a < -.1)", "$?(@.\"a\" < -0.1)"),
    ("$ ? (@.a < +.1)", "$?(@.\"a\" < 0.1)"),
    ("$ ? (@.a < 0.1)", "$?(@.\"a\" < 0.1)"),
    ("$ ? (@.a < -0.1)", "$?(@.\"a\" < -0.1)"),
    ("$ ? (@.a < +0.1)", "$?(@.\"a\" < 0.1)"),
    ("$ ? (@.a < 10.1)", "$?(@.\"a\" < 10.1)"),
    ("$ ? (@.a < -10.1)", "$?(@.\"a\" < -10.1)"),
    ("$ ? (@.a < +10.1)", "$?(@.\"a\" < 10.1)"),
    ("$ ? (@.a < 1e1)", "$?(@.\"a\" < 10)"),
    ("$ ? (@.a < -1e1)", "$?(@.\"a\" < -10)"),
    ("$ ? (@.a < +1e1)", "$?(@.\"a\" < 10)"),
    ("$ ? (@.a < .1e1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < -.1e1)", "$?(@.\"a\" < -1)"),
    ("$ ? (@.a < +.1e1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < 0.1e1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < -0.1e1)", "$?(@.\"a\" < -1)"),
    ("$ ? (@.a < +0.1e1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < 10.1e1)", "$?(@.\"a\" < 101)"),
    ("$ ? (@.a < -10.1e1)", "$?(@.\"a\" < -101)"),
    ("$ ? (@.a < +10.1e1)", "$?(@.\"a\" < 101)"),
    ("$ ? (@.a < 1e-1)", "$?(@.\"a\" < 0.1)"),
    ("$ ? (@.a < -1e-1)", "$?(@.\"a\" < -0.1)"),
    ("$ ? (@.a < +1e-1)", "$?(@.\"a\" < 0.1)"),
    ("$ ? (@.a < .1e-1)", "$?(@.\"a\" < 0.01)"),
    ("$ ? (@.a < -.1e-1)", "$?(@.\"a\" < -0.01)"),
    ("$ ? (@.a < +.1e-1)", "$?(@.\"a\" < 0.01)"),
    ("$ ? (@.a < 0.1e-1)", "$?(@.\"a\" < 0.01)"),
    ("$ ? (@.a < -0.1e-1)", "$?(@.\"a\" < -0.01)"),
    ("$ ? (@.a < +0.1e-1)", "$?(@.\"a\" < 0.01)"),
    ("$ ? (@.a < 10.1e-1)", "$?(@.\"a\" < 1.01)"),
    ("$ ? (@.a < -10.1e-1)", "$?(@.\"a\" < -1.01)"),
    ("$ ? (@.a < +10.1e-1)", "$?(@.\"a\" < 1.01)"),
    ("$ ? (@.a < 1e+1)", "$?(@.\"a\" < 10)"),
    ("$ ? (@.a < -1e+1)", "$?(@.\"a\" < -10)"),
    ("$ ? (@.a < +1e+1)", "$?(@.\"a\" < 10)"),
    ("$ ? (@.a < .1e+1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < -.1e+1)", "$?(@.\"a\" < -1)"),
    ("$ ? (@.a < +.1e+1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < 0.1e+1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < -0.1e+1)", "$?(@.\"a\" < -1)"),
    ("$ ? (@.a < +0.1e+1)", "$?(@.\"a\" < 1)"),
    ("$ ? (@.a < 10.1e+1)", "$?(@.\"a\" < 101)"),
    ("$ ? (@.a < -10.1e+1)", "$?(@.\"a\" < -101)"),
    ("$ ? (@.a < +10.1e+1)", "$?(@.\"a\" < 101)"),
    ("0", "0"),
    ("0.0", "0.0"),
    ("0.000", "0.000"),
    ("0.000e1", "0.00"),
    ("0.000e2", "0.0"),
    ("0.000e3", "0"),
    ("0.0010", "0.0010"),
    ("0.0010e-1", "0.00010"),
    ("0.0010e+1", "0.010"),
    ("0.0010e+2", "0.10"),
    (".001", "0.001"),
    (".001e1", "0.01"),
    ("1.", "1"),
    ("1.e1", "10"),
    ("1.2.e", "(1.2).\"e\""),
    ("(1.2).e", "(1.2).\"e\""),
    ("1e3", "1000"),
    ("1.e3", "1000"),
    ("1.e3.e", "(1000).\"e\""),
    ("1.e3.e4", "(1000).\"e4\""),
    ("1.2e3", "1200"),
    ("1.2.e3", "(1.2).\"e3\""),
    ("(1.2).e3", "(1.2).\"e3\""),
    ("1..e", "(1).\"e\""),
    ("1..e3", "(1).\"e3\""),
    ("(1.).e", "(1).\"e\""),
    ("(1.).e3", "(1).\"e3\""),
    ("1?(2>3)", "(1)?(2 > 3)"),
    ("0b100101", "37"),
    ("0o273", "187"),
    ("0x42F", "1071"),
    ("1_000_000", "1000000"),
    ("1_2_3", "123"),
    ("0x1EEE_FFFF", "518979583"),
    ("0o2_73", "187"),
    ("0b10_0101", "37"),
    ("1_000.000_005", "1000.000005"),
    ("1_000.", "1000"),
    (".000_005", "0.000005"),
    ("1_000.5e0_1", "10005"),
];

pub static ERR_VECTORS: &[(&str, &str, Option<&str>)] = &[
    ("", "invalid input syntax for type jsonpath: \"\"", None),
    ("last", "LAST is allowed only in array subscripts", None),
    (
        "$ ? (last > 0)",
        "LAST is allowed only in array subscripts",
        None,
    ),
    (
        "1.type()",
        "trailing junk after numeric literal at or near \"1.t\" of jsonpath input",
        None,
    ),
    (
        "$ ? (@ like_regex \"(invalid pattern\")",
        "invalid regular expression: parentheses () not balanced",
        None,
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"xsms\")",
        "XQuery \"x\" flag (expanded regular expressions) is not implemented",
        None,
    ),
    (
        "$ ? (@ like_regex \"pattern\" flag \"a\")",
        "invalid input syntax for type jsonpath",
        Some("Unrecognized flag character \"a\" in LIKE_REGEX predicate."),
    ),
    ("@ + 1", "@ is not allowed in root expressions", None),
    (
        "00",
        "trailing junk after numeric literal at or near \"00\" of jsonpath input",
        None,
    ),
    ("0755", "syntax error at end of jsonpath input", None),
    (
        "1a",
        "trailing junk after numeric literal at or near \"1a\" of jsonpath input",
        None,
    ),
    (
        "1e",
        "trailing junk after numeric literal at or near \"1e\" of jsonpath input",
        None,
    ),
    (
        "1.e",
        "trailing junk after numeric literal at or near \"1.e\" of jsonpath input",
        None,
    ),
    (
        "1.2a",
        "trailing junk after numeric literal at or near \"1.2a\" of jsonpath input",
        None,
    ),
    (
        "1.2e",
        "trailing junk after numeric literal at or near \"1.2e\" of jsonpath input",
        None,
    ),
    (
        "1.2e3a",
        "trailing junk after numeric literal at or near \"1.2e3a\" of jsonpath input",
        None,
    ),
    (
        "0b",
        "trailing junk after numeric literal at or near \"0b\" of jsonpath input",
        None,
    ),
    (
        "1b",
        "trailing junk after numeric literal at or near \"1b\" of jsonpath input",
        None,
    ),
    ("0b0x", "syntax error at end of jsonpath input", None),
    (
        "0o",
        "trailing junk after numeric literal at or near \"0o\" of jsonpath input",
        None,
    ),
    (
        "1o",
        "trailing junk after numeric literal at or near \"1o\" of jsonpath input",
        None,
    ),
    ("0o0x", "syntax error at end of jsonpath input", None),
    (
        "0x",
        "trailing junk after numeric literal at or near \"0x\" of jsonpath input",
        None,
    ),
    (
        "1x",
        "trailing junk after numeric literal at or near \"1x\" of jsonpath input",
        None,
    ),
    ("0x0y", "syntax error at end of jsonpath input", None),
    ("_100", "syntax error at end of jsonpath input", None),
    (
        "100_",
        "trailing junk after numeric literal at or near \"100_\" of jsonpath input",
        None,
    ),
    ("100__000", "syntax error at end of jsonpath input", None),
    ("_1_000.5", "syntax error at end of jsonpath input", None),
    (
        "1_000_.5",
        "trailing junk after numeric literal at or near \"1_000_\" of jsonpath input",
        None,
    ),
    (
        "1_000._5",
        "trailing junk after numeric literal at or near \"1_000._\" of jsonpath input",
        None,
    ),
    (
        "1_000.5_",
        "trailing junk after numeric literal at or near \"1_000.5_\" of jsonpath input",
        None,
    ),
    (
        "1_000.5e_1",
        "trailing junk after numeric literal at or near \"1_000.5e\" of jsonpath input",
        None,
    ),
    ("0b_10_0101", "syntax error at end of jsonpath input", None),
    ("0o_273", "syntax error at end of jsonpath input", None),
    ("0x_42F", "syntax error at end of jsonpath input", None),
];
