// Vectors generated by running the vendored src/common/pg_lzcompress.c (see data/).
mod c_vectors {
    include!("data/c_vectors.rs");
}
use core::mem::MaybeUninit;

use c_vectors::*;
use pglz::{
    pglz_compress_into, pglz_decompress, pglz_max_output, pglz_maximum_compressed_size,
    PGLZ_STRATEGY_ALWAYS, PGLZ_STRATEGY_DEFAULT,
};

struct Prng(u64);
impl Prng {
    fn new() -> Self {
        Prng(0x243f6a8885a308d3)
    }
    fn next_byte(&mut self) -> u8 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (self.0 >> 56) as u8
    }
}

// Keep in sync with gen_input() in data/gen_vectors.c.
fn gen_input(kind: &str, n: usize) -> Vec<u8> {
    let mut prng = Prng::new();
    match kind {
        "rep" => {
            let phrase = b"the quick brown fox jumps over a lazy dog #";
            (0..n).map(|i| phrase[i % phrase.len()]).collect()
        }
        "zeros" => vec![0u8; n],
        "digits" => {
            let digits = b"0123456789.";
            (0..n)
                .map(|_| digits[(prng.next_byte() % 11) as usize])
                .collect()
        }
        "high" => (0..n).map(|_| 0x80 | (prng.next_byte() % 7) * 17).collect(),
        "mixed" => {
            let mut buf = Vec::with_capacity(n);
            for i in 0..n {
                let b = if i % 61 >= 37 && i >= 64 {
                    buf[i - 64]
                } else {
                    prng.next_byte()
                };
                buf.push(b);
            }
            buf
        }
        other => panic!("unknown kind {other}"),
    }
}

fn strategy(name: &str) -> &'static pglz::PglzStrategy {
    match name {
        "default" => &PGLZ_STRATEGY_DEFAULT,
        "always" => &PGLZ_STRATEGY_ALWAYS,
        other => panic!("unknown strategy {other}"),
    }
}

#[test]
fn decompress_matches_c_streams() {
    for case in CASES {
        let input = gen_input(case.kind, case.rawsize as usize);
        let mut dest = vec![MaybeUninit::<u8>::uninit(); case.rawsize as usize];
        let n = pglz_decompress(case.compressed, &mut dest, true).unwrap_or_else(|| {
            panic!(
                "{}/{}: corrupt verdict on valid C stream",
                case.kind, case.rawsize
            )
        });
        assert_eq!(n, case.rawsize as usize, "{}/{}", case.kind, case.rawsize);
        let out: Vec<u8> = dest[..n]
            .iter()
            .map(|b| unsafe { b.assume_init() })
            .collect();
        assert_eq!(out, input, "{}/{}", case.kind, case.rawsize);
    }
}

#[test]
fn decompress_prefix_slices_match_input() {
    for case in CASES {
        let input = gen_input(case.kind, case.rawsize as usize);
        for frac in [3usize, 7] {
            let take = (case.rawsize as usize / frac).max(1);
            let mut dest = vec![MaybeUninit::<u8>::uninit(); take];
            let n = pglz_decompress(case.compressed, &mut dest, false).unwrap();
            assert_eq!(n, take, "{}/{}", case.kind, case.rawsize);
            let out: Vec<u8> = dest[..n]
                .iter()
                .map(|b| unsafe { b.assume_init() })
                .collect();
            assert_eq!(out, &input[..take], "{}/{}", case.kind, case.rawsize);
        }
    }
}

#[test]
fn compress_matches_c_streams() {
    let platform_signed = (0x80u8 as core::ffi::c_char as i32) < 0;
    for case in CASES {
        let input = gen_input(case.kind, case.rawsize as usize);
        let mut dest = vec![MaybeUninit::<u8>::uninit(); pglz_max_output(input.len())];
        let n = pglz_compress_into(&input, &mut dest, strategy(case.strategy))
            .unwrap_or_else(|| panic!("{}/{}: C compressed this input", case.kind, case.rawsize));
        let out: Vec<u8> = dest[..n]
            .iter()
            .map(|b| unsafe { b.assume_init() })
            .collect();
        if platform_signed == CHAR_IS_SIGNED {
            assert_eq!(out, case.compressed, "{}/{}", case.kind, case.rawsize);
        } else {
            // Different char signedness picks different hash buckets: streams
            // are valid but not byte-identical to the vectors; roundtrip only.
            let mut back = vec![MaybeUninit::<u8>::uninit(); case.rawsize as usize];
            let r = pglz_decompress(&out, &mut back, true).unwrap();
            let back: Vec<u8> = back[..r]
                .iter()
                .map(|b| unsafe { b.assume_init() })
                .collect();
            assert_eq!(back, input, "{}/{}", case.kind, case.rawsize);
        }
    }
}

#[test]
fn maximum_compressed_size_matches_c() {
    for &(rawsize, total, expect) in MAX_COMPRESSED_SIZE {
        assert_eq!(pglz_maximum_compressed_size(rawsize, total), expect);
    }
}
