#![allow(non_snake_case)]

// conv.c engine (radix trees, combined maps, mule/latin helpers) + all 25
// conversion_procs modules of C 18.3. Tables in src/maps/ are generated by
// scripts/gen_radix_tables.py from the C tree, never hand-transcribed.

mod maps;

// pub visibility: proofs/mbconv calls the fc_* wrappers directly (CBMC
// cannot devirtualize CONV_BUILTINS fn pointers); no behavior change.
pub mod cyrillic_and_mic;
pub mod euc2004_sjis2004;
pub mod euc_cn_and_mic;
pub mod euc_jp_and_sjis;
pub mod euc_kr_and_mic;
pub mod euc_tw_and_big5;
pub mod latin2_and_win1250;
pub mod latin_and_mic;
pub mod utf8_procs;

use datum::Datum;
use mbutils::{
    check_encoding_conversion_args, report_invalid_encoding, report_untranslatable_char,
};
use types_core::Oid;
use types_error::{PgError, PgResult, ERRCODE_INTERNAL_ERROR, ERRCODE_INVALID_PARAMETER_VALUE};
use types_fmgr::{FmgrBuiltin, FmgrInfo, FunctionCallInfoBaseData as Fcinfo};
use wchar::{
    pg_enc, pg_encoding_verifymbchar, pg_mule_mblen, pg_utf8_islegal, pg_utf_mblen,
    pg_valid_encoding, PG_ISO_8859_5, PG_ISO_8859_6, PG_ISO_8859_7, PG_ISO_8859_8, PG_LATIN1,
    PG_LATIN10, PG_LATIN2, PG_LATIN3, PG_LATIN4, PG_LATIN5, PG_LATIN6, PG_LATIN7, PG_LATIN8,
    PG_LATIN9, PG_MULE_INTERNAL, PG_UTF8, PG_WIN1250, PG_WIN1251, PG_WIN1252, PG_WIN1253,
    PG_WIN1254, PG_WIN1255, PG_WIN1256, PG_WIN1257, PG_WIN1258, PG_WIN866, PG_WIN874,
};

// pg_wchar.h values; wchar keeps its copies private.
const HIGHBIT: u8 = 0x80;
const SS2: u8 = 0x8e;
const SS3: u8 = 0x8f;
const LC_ISO8859_1: u8 = 0x81;
const LC_ISO8859_2: u8 = 0x82;
const LC_ISO8859_3: u8 = 0x83;
const LC_ISO8859_4: u8 = 0x84;
const LC_KOI8_R: u8 = 0x8b;
const LC_GB2312_80: u8 = 0x91;
const LC_JISX0208: u8 = 0x92;
const LC_KS5601: u8 = 0x93;
const LC_JISX0212: u8 = 0x94;
const LC_CNS11643_1: u8 = 0x95;
const LC_CNS11643_2: u8 = 0x96;
const LC_JISX0201K: u8 = 0x89;
const LC_CNS11643_3: u8 = 0xf6;
const LC_CNS11643_7: u8 = 0xfa;
const LC_CNS11643_4: u8 = 0xf7;
const LCPRV2_B: u8 = 0x9d;

#[inline]
fn is_highbit_set(b: u8) -> bool {
    b & HIGHBIT != 0
}

pub struct UtfToLocalCombined {
    pub utf1: u32,
    pub utf2: u32,
    pub code: u32,
}

pub struct LocalToUtfCombined {
    pub code: u32,
    pub utf1: u32,
    pub utf2: u32,
}

pub struct PgMbRadixTree {
    pub chars16: &'static [u16],
    pub chars32: &'static [u32],
    pub b1root: u32,
    pub b1_lower: u8,
    pub b1_upper: u8,
    pub b2root: u32,
    pub b2_1_lower: u8,
    pub b2_1_upper: u8,
    pub b2_2_lower: u8,
    pub b2_2_upper: u8,
    pub b3root: u32,
    pub b3_1_lower: u8,
    pub b3_1_upper: u8,
    pub b3_2_lower: u8,
    pub b3_2_upper: u8,
    pub b3_3_lower: u8,
    pub b3_3_upper: u8,
    pub b4root: u32,
    pub b4_1_lower: u8,
    pub b4_1_upper: u8,
    pub b4_2_lower: u8,
    pub b4_2_upper: u8,
    pub b4_3_lower: u8,
    pub b4_3_upper: u8,
    pub b4_4_lower: u8,
    pub b4_4_upper: u8,
}

impl PgMbRadixTree {
    #[inline]
    fn get(&self, idx: u32) -> u32 {
        if !self.chars32.is_empty() {
            self.chars32[idx as usize]
        } else {
            self.chars16[idx as usize] as u32
        }
    }
}

fn pg_mb_radix_conv(rt: &PgMbRadixTree, l: i32, b1: u8, b2: u8, b3: u8, b4: u8) -> u32 {
    match l {
        4 => {
            if b1 < rt.b4_1_lower
                || b1 > rt.b4_1_upper
                || b2 < rt.b4_2_lower
                || b2 > rt.b4_2_upper
                || b3 < rt.b4_3_lower
                || b3 > rt.b4_3_upper
                || b4 < rt.b4_4_lower
                || b4 > rt.b4_4_upper
            {
                return 0;
            }
            let mut idx = rt.b4root;
            idx = rt.get(b1 as u32 + idx - rt.b4_1_lower as u32);
            idx = rt.get(b2 as u32 + idx - rt.b4_2_lower as u32);
            idx = rt.get(b3 as u32 + idx - rt.b4_3_lower as u32);
            rt.get(b4 as u32 + idx - rt.b4_4_lower as u32)
        }
        3 => {
            if b2 < rt.b3_1_lower
                || b2 > rt.b3_1_upper
                || b3 < rt.b3_2_lower
                || b3 > rt.b3_2_upper
                || b4 < rt.b3_3_lower
                || b4 > rt.b3_3_upper
            {
                return 0;
            }
            let mut idx = rt.b3root;
            idx = rt.get(b2 as u32 + idx - rt.b3_1_lower as u32);
            idx = rt.get(b3 as u32 + idx - rt.b3_2_lower as u32);
            rt.get(b4 as u32 + idx - rt.b3_3_lower as u32)
        }
        2 => {
            if b3 < rt.b2_1_lower || b3 > rt.b2_1_upper || b4 < rt.b2_2_lower || b4 > rt.b2_2_upper
            {
                return 0;
            }
            let mut idx = rt.b2root;
            idx = rt.get(b3 as u32 + idx - rt.b2_1_lower as u32);
            rt.get(b4 as u32 + idx - rt.b2_2_lower as u32)
        }
        1 => {
            if b4 < rt.b1_lower || b4 > rt.b1_upper {
                return 0;
            }
            rt.get(b4 as u32 + rt.b1root - rt.b1_lower as u32)
        }
        _ => 0,
    }
}

/// Raw output cursor over the caller's conversion buffer.
struct Dst(*mut u8);

impl Dst {
    /// SAFETY: caller guarantees the mbutils conversion-buffer contract
    /// (capacity >= srclen * MAX_CONVERSION_GROWTH + 1); each source byte
    /// emits at most 4 output bytes plus one final NUL.
    #[inline]
    unsafe fn push(&mut self, b: u8) {
        unsafe {
            *self.0 = b;
            self.0 = self.0.add(1);
        }
    }

    unsafe fn store_coded_char(&mut self, code: u32) {
        unsafe {
            if code & 0xff00_0000 != 0 {
                self.push((code >> 24) as u8);
            }
            if code & 0x00ff_0000 != 0 {
                self.push((code >> 16) as u8);
            }
            if code & 0x0000_ff00 != 0 {
                self.push((code >> 8) as u8);
            }
            if code & 0x0000_00ff != 0 {
                self.push(code as u8);
            }
        }
    }
}

#[track_caller]
#[cold]
fn invalid_encoding_number(encoding: pg_enc) -> Box<PgError> {
    Box::new(
        PgError::error(format!("invalid encoding number: {encoding}"))
            .with_sqlstate(ERRCODE_INVALID_PARAMETER_VALUE),
    )
}

/// C `UtfToLocal` (map always present: every 18.3 caller passes one; C's NULL
/// map arm is dead here). Writes NUL-terminated bytes through `dest`; returns
/// source bytes consumed (< `src.len()` only when `no_error`).
///
/// # Safety
/// `dest` must satisfy the mbutils conversion-buffer contract:
/// `src.len() * MAX_CONVERSION_GROWTH + 1` writable bytes.
pub unsafe fn UtfToLocal(
    src: &[u8],
    dest: *mut u8,
    map: &PgMbRadixTree,
    cmap: &[UtfToLocalCombined],
    conv_func: Option<fn(u32) -> u32>,
    encoding: pg_enc,
    no_error: bool,
) -> PgResult<i32> {
    if !pg_valid_encoding(encoding) {
        return Err(invalid_encoding_number(encoding));
    }
    let mut out = Dst(dest);
    let mut pos = 0usize;
    loop {
        let remaining = src.len() - pos;
        if remaining == 0 || src[pos] == 0 {
            break;
        }
        let l = pg_utf_mblen(&src[pos..]);
        if remaining < l as usize {
            break;
        }
        if !pg_utf8_islegal(&src[pos..], l) {
            break;
        }
        if l == 1 {
            unsafe { out.push(src[pos]) };
            pos += 1;
            continue;
        }
        let (b1, b2, b3, b4) = match l {
            2 => (0, 0, src[pos], src[pos + 1]),
            3 => (0, src[pos], src[pos + 1], src[pos + 2]),
            _ => (src[pos], src[pos + 1], src[pos + 2], src[pos + 3]),
        };
        let iutf = ((b1 as u32) << 24) | ((b2 as u32) << 16) | ((b3 as u32) << 8) | b4 as u32;
        if !cmap.is_empty() && remaining > l as usize {
            let pos2 = pos + l as usize;
            let rem2 = src.len() - pos2;
            let l2 = pg_utf_mblen(&src[pos2..]);
            if rem2 < l2 as usize {
                // C backs up to the first char but keeps the reduced length,
                // so the reported byte sequence is clipped to the truncated
                // tail's length.
                if !no_error {
                    return Err(report_invalid_encoding(PG_UTF8, &src[pos..pos + rem2]));
                }
                break;
            }
            if !pg_utf8_islegal(&src[pos2..], l2) {
                if !no_error {
                    return Err(report_invalid_encoding(PG_UTF8, &src[pos2..]));
                }
                break;
            }
            if l2 > 1 {
                let mut iutf2 = 0u32;
                for &b in &src[pos2..pos2 + l2 as usize] {
                    iutf2 = (iutf2 << 8) | b as u32;
                }
                if let Ok(i) = cmap.binary_search_by(|e| (e.utf1, e.utf2).cmp(&(iutf, iutf2))) {
                    unsafe { out.store_coded_char(cmap[i].code) };
                    pos = pos2 + l2 as usize;
                    continue;
                }
            }
        }
        let converted = pg_mb_radix_conv(map, l, b1, b2, b3, b4);
        if converted != 0 {
            unsafe { out.store_coded_char(converted) };
            pos += l as usize;
            continue;
        }
        if let Some(f) = conv_func {
            let converted = f(iutf);
            if converted != 0 {
                unsafe { out.store_coded_char(converted) };
                pos += l as usize;
                continue;
            }
        }
        if no_error {
            break;
        }
        return Err(report_untranslatable_char(PG_UTF8, encoding, &src[pos..]));
    }
    if pos < src.len() && !no_error {
        return Err(report_invalid_encoding(PG_UTF8, &src[pos..]));
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

/// C `LocalToUtf`; see [`UtfToLocal`].
///
/// # Safety
/// Same `dest` contract as [`UtfToLocal`].
pub unsafe fn LocalToUtf(
    src: &[u8],
    dest: *mut u8,
    map: &PgMbRadixTree,
    cmap: &[LocalToUtfCombined],
    conv_func: Option<fn(u32) -> u32>,
    encoding: pg_enc,
    no_error: bool,
) -> PgResult<i32> {
    if !pg_valid_encoding(encoding) {
        return Err(invalid_encoding_number(encoding));
    }
    let mut out = Dst(dest);
    let mut pos = 0usize;
    loop {
        let remaining = src.len() - pos;
        if remaining == 0 || src[pos] == 0 {
            break;
        }
        if src[pos] & 0x80 == 0 {
            unsafe { out.push(src[pos]) };
            pos += 1;
            continue;
        }
        let l = pg_encoding_verifymbchar(encoding, &src[pos..]);
        if l < 0 {
            break;
        }
        let (b1, b2, b3, b4) = match l {
            1 => (0, 0, 0, src[pos]),
            2 => (0, 0, src[pos], src[pos + 1]),
            3 => (0, src[pos], src[pos + 1], src[pos + 2]),
            _ => (src[pos], src[pos + 1], src[pos + 2], src[pos + 3]),
        };
        let iiso = ((b1 as u32) << 24) | ((b2 as u32) << 16) | ((b3 as u32) << 8) | b4 as u32;
        let converted = pg_mb_radix_conv(map, l, b1, b2, b3, b4);
        if converted != 0 {
            unsafe { out.store_coded_char(converted) };
            pos += l as usize;
            continue;
        }
        if let Ok(i) = cmap.binary_search_by(|e| e.code.cmp(&iiso)) {
            unsafe {
                out.store_coded_char(cmap[i].utf1);
                out.store_coded_char(cmap[i].utf2);
            }
            pos += l as usize;
            continue;
        }
        if let Some(f) = conv_func {
            let converted = f(iiso);
            if converted != 0 {
                unsafe { out.store_coded_char(converted) };
                pos += l as usize;
                continue;
            }
        }
        if no_error {
            break;
        }
        return Err(report_untranslatable_char(encoding, PG_UTF8, &src[pos..]));
    }
    if pos < src.len() && !no_error {
        return Err(report_invalid_encoding(encoding, &src[pos..]));
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

/// C `local2local`: single-byte charset to single-byte charset via `tab`
/// (indexed by `c - 0x80`, 0 = untranslatable).
///
/// # Safety
/// Same `dest` contract as [`UtfToLocal`].
pub(crate) unsafe fn local2local(
    src: &[u8],
    dest: *mut u8,
    src_encoding: pg_enc,
    dest_encoding: pg_enc,
    tab: &[u8; 128],
    no_error: bool,
) -> PgResult<i32> {
    let mut out = Dst(dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let c1 = src[pos];
        if c1 == 0 {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(src_encoding, &src[pos..]));
        }
        if !is_highbit_set(c1) {
            unsafe { out.push(c1) };
        } else {
            let c2 = tab[(c1 - HIGHBIT) as usize];
            if c2 != 0 {
                unsafe { out.push(c2) };
            } else {
                if no_error {
                    break;
                }
                return Err(report_untranslatable_char(
                    src_encoding,
                    dest_encoding,
                    &src[pos..],
                ));
            }
        }
        pos += 1;
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

/// C `latin2mic`: LATINn -> MIC when local codes map directly.
///
/// # Safety
/// Same `dest` contract as [`UtfToLocal`] (2 output bytes per input byte max).
pub(crate) unsafe fn latin2mic(
    src: &[u8],
    dest: *mut u8,
    lc: u8,
    encoding: pg_enc,
    no_error: bool,
) -> PgResult<i32> {
    let mut out = Dst(dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let c1 = src[pos];
        if c1 == 0 {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(encoding, &src[pos..]));
        }
        unsafe {
            if is_highbit_set(c1) {
                out.push(lc);
            }
            out.push(c1);
        }
        pos += 1;
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

/// C `mic2latin`.
///
/// # Safety
/// Same `dest` contract as [`UtfToLocal`].
pub(crate) unsafe fn mic2latin(
    src: &[u8],
    dest: *mut u8,
    lc: u8,
    encoding: pg_enc,
    no_error: bool,
) -> PgResult<i32> {
    let mut out = Dst(dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let c1 = src[pos];
        if c1 == 0 {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_MULE_INTERNAL, &src[pos..]));
        }
        if !is_highbit_set(c1) {
            unsafe { out.push(c1) };
            pos += 1;
            continue;
        }
        let l = pg_mule_mblen(&src[pos..]);
        if src.len() - pos < l as usize {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_MULE_INTERNAL, &src[pos..]));
        }
        if l != 2 || c1 != lc || !is_highbit_set(src[pos + 1]) {
            if no_error {
                break;
            }
            return Err(report_untranslatable_char(
                PG_MULE_INTERNAL,
                encoding,
                &src[pos..],
            ));
        }
        unsafe { out.push(src[pos + 1]) };
        pos += 2;
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

/// C `latin2mic_with_table`.
///
/// # Safety
/// Same `dest` contract as [`UtfToLocal`].
pub(crate) unsafe fn latin2mic_with_table(
    src: &[u8],
    dest: *mut u8,
    lc: u8,
    encoding: pg_enc,
    tab: &[u8; 128],
    no_error: bool,
) -> PgResult<i32> {
    let mut out = Dst(dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let c1 = src[pos];
        if c1 == 0 {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(encoding, &src[pos..]));
        }
        if !is_highbit_set(c1) {
            unsafe { out.push(c1) };
        } else {
            let c2 = tab[(c1 - HIGHBIT) as usize];
            if c2 != 0 {
                unsafe {
                    out.push(lc);
                    out.push(c2);
                }
            } else {
                if no_error {
                    break;
                }
                return Err(report_untranslatable_char(
                    encoding,
                    PG_MULE_INTERNAL,
                    &src[pos..],
                ));
            }
        }
        pos += 1;
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

/// C `mic2latin_with_table`.
///
/// # Safety
/// Same `dest` contract as [`UtfToLocal`].
pub(crate) unsafe fn mic2latin_with_table(
    src: &[u8],
    dest: *mut u8,
    lc: u8,
    encoding: pg_enc,
    tab: &[u8; 128],
    no_error: bool,
) -> PgResult<i32> {
    let mut out = Dst(dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let c1 = src[pos];
        if c1 == 0 {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_MULE_INTERNAL, &src[pos..]));
        }
        if !is_highbit_set(c1) {
            unsafe { out.push(c1) };
            pos += 1;
            continue;
        }
        let l = pg_mule_mblen(&src[pos..]);
        if src.len() - pos < l as usize {
            if no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_MULE_INTERNAL, &src[pos..]));
        }
        let c2 = if l == 2 && c1 == lc && is_highbit_set(src[pos + 1]) {
            tab[(src[pos + 1] - HIGHBIT) as usize]
        } else {
            0
        };
        if c2 == 0 {
            if no_error {
                break;
            }
            return Err(report_untranslatable_char(
                PG_MULE_INTERNAL,
                encoding,
                &src[pos..],
            ));
        }
        unsafe { out.push(c2) };
        pos += 2;
    }
    unsafe { *out.0 = 0 };
    Ok(pos as i32)
}

struct ConvArgs {
    src_encoding: pg_enc,
    dest_encoding: pg_enc,
    src_ptr: *const u8,
    dest: *mut u8,
    len: i32,
    no_error: bool,
}

impl ConvArgs {
    /// SAFETY: callers arrive only through the conversion-proc fcinfo contract
    /// (mbutils convert_with_proc / C FunctionCall6): arg2 = live source
    /// pointer readable for arg4 bytes, arg3 = destination buffer of
    /// len * MAX_CONVERSION_GROWTH + 1 writable bytes, len >= 0.
    unsafe fn from(fcinfo: &Fcinfo) -> Self {
        unsafe {
            ConvArgs {
                src_encoding: fcinfo.arg_i32(0),
                dest_encoding: fcinfo.arg_i32(1),
                src_ptr: fcinfo.arg_ptr(2),
                dest: fcinfo.arg_ptr(3) as *mut u8,
                len: fcinfo.arg_i32(4),
                no_error: fcinfo.arg_bool(5),
            }
        }
    }

    fn src(&self) -> &[u8] {
        // SAFETY: see from(); check_encoding_conversion_args rejected len < 0.
        unsafe { core::slice::from_raw_parts(self.src_ptr, self.len as usize) }
    }
}

// utf8_and_iso8859_1.c: LATIN1 is algorithmic (Unicode 0x80..=0xFF), no map.
pub fn fc_iso8859_1_to_utf8(
    _flinfo: Option<&mut FmgrInfo>,
    fcinfo: &mut Fcinfo,
) -> PgResult<Datum> {
    let a = unsafe { ConvArgs::from(fcinfo) };
    check_encoding_conversion_args(a.src_encoding, a.dest_encoding, a.len, PG_LATIN1, PG_UTF8)?;
    let src = a.src();
    let mut out = Dst(a.dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let c = src[pos];
        if c == 0 {
            if a.no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_LATIN1, &src[pos..]));
        }
        // SAFETY: Dst buffer contract (ConvArgs::from); <=2 bytes per input byte.
        unsafe {
            if c & 0x80 == 0 {
                out.push(c);
            } else {
                out.push((c >> 6) | 0xc0);
                out.push((c & 0x3f) | 0x80);
            }
        }
        pos += 1;
    }
    unsafe { *out.0 = 0 };
    Ok(Datum::from_i32(pos as i32))
}

pub fn fc_utf8_to_iso8859_1(
    _flinfo: Option<&mut FmgrInfo>,
    fcinfo: &mut Fcinfo,
) -> PgResult<Datum> {
    let a = unsafe { ConvArgs::from(fcinfo) };
    check_encoding_conversion_args(a.src_encoding, a.dest_encoding, a.len, PG_UTF8, PG_LATIN1)?;
    let src = a.src();
    let mut out = Dst(a.dest);
    let mut pos = 0usize;
    while pos < src.len() {
        let remaining = src.len() - pos;
        let c = src[pos];
        if c == 0 {
            if a.no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_UTF8, &src[pos..]));
        }
        if c & 0x80 == 0 {
            unsafe { out.push(c) };
            pos += 1;
            continue;
        }
        let l = pg_utf_mblen(&src[pos..]);
        if l as usize > remaining || !pg_utf8_islegal(&src[pos..], l) {
            if a.no_error {
                break;
            }
            return Err(report_invalid_encoding(PG_UTF8, &src[pos..]));
        }
        if l != 2 {
            if a.no_error {
                break;
            }
            return Err(report_untranslatable_char(PG_UTF8, PG_LATIN1, &src[pos..]));
        }
        let c1 = (src[pos + 1] & 0x3f) as u16;
        let code = (((c as u16) & 0x1f) << 6) | c1;
        if (0x80..=0xff).contains(&code) {
            unsafe { out.push(code as u8) };
            pos += 2;
        } else {
            if a.no_error {
                break;
            }
            return Err(report_untranslatable_char(PG_UTF8, PG_LATIN1, &src[pos..]));
        }
    }
    unsafe { *out.0 = 0 };
    Ok(Datum::from_i32(pos as i32))
}

fn win_maps(encoding: pg_enc) -> Option<(&'static PgMbRadixTree, &'static PgMbRadixTree)> {
    use maps::win as t;
    match encoding {
        PG_WIN866 => Some((&t::WIN866_TO_UNICODE_TREE, &t::WIN866_FROM_UNICODE_TREE)),
        PG_WIN874 => Some((&t::WIN874_TO_UNICODE_TREE, &t::WIN874_FROM_UNICODE_TREE)),
        PG_WIN1250 => Some((&t::WIN1250_TO_UNICODE_TREE, &t::WIN1250_FROM_UNICODE_TREE)),
        PG_WIN1251 => Some((&t::WIN1251_TO_UNICODE_TREE, &t::WIN1251_FROM_UNICODE_TREE)),
        PG_WIN1252 => Some((&t::WIN1252_TO_UNICODE_TREE, &t::WIN1252_FROM_UNICODE_TREE)),
        PG_WIN1253 => Some((&t::WIN1253_TO_UNICODE_TREE, &t::WIN1253_FROM_UNICODE_TREE)),
        PG_WIN1254 => Some((&t::WIN1254_TO_UNICODE_TREE, &t::WIN1254_FROM_UNICODE_TREE)),
        PG_WIN1255 => Some((&t::WIN1255_TO_UNICODE_TREE, &t::WIN1255_FROM_UNICODE_TREE)),
        PG_WIN1256 => Some((&t::WIN1256_TO_UNICODE_TREE, &t::WIN1256_FROM_UNICODE_TREE)),
        PG_WIN1257 => Some((&t::WIN1257_TO_UNICODE_TREE, &t::WIN1257_FROM_UNICODE_TREE)),
        PG_WIN1258 => Some((&t::WIN1258_TO_UNICODE_TREE, &t::WIN1258_FROM_UNICODE_TREE)),
        _ => None,
    }
}

fn iso8859_maps(encoding: pg_enc) -> Option<(&'static PgMbRadixTree, &'static PgMbRadixTree)> {
    use maps::iso8859 as t;
    match encoding {
        PG_LATIN2 => Some((
            &t::ISO8859_2_TO_UNICODE_TREE,
            &t::ISO8859_2_FROM_UNICODE_TREE,
        )),
        PG_LATIN3 => Some((
            &t::ISO8859_3_TO_UNICODE_TREE,
            &t::ISO8859_3_FROM_UNICODE_TREE,
        )),
        PG_LATIN4 => Some((
            &t::ISO8859_4_TO_UNICODE_TREE,
            &t::ISO8859_4_FROM_UNICODE_TREE,
        )),
        PG_LATIN5 => Some((
            &t::ISO8859_9_TO_UNICODE_TREE,
            &t::ISO8859_9_FROM_UNICODE_TREE,
        )),
        PG_LATIN6 => Some((
            &t::ISO8859_10_TO_UNICODE_TREE,
            &t::ISO8859_10_FROM_UNICODE_TREE,
        )),
        PG_LATIN7 => Some((
            &t::ISO8859_13_TO_UNICODE_TREE,
            &t::ISO8859_13_FROM_UNICODE_TREE,
        )),
        PG_LATIN8 => Some((
            &t::ISO8859_14_TO_UNICODE_TREE,
            &t::ISO8859_14_FROM_UNICODE_TREE,
        )),
        PG_LATIN9 => Some((
            &t::ISO8859_15_TO_UNICODE_TREE,
            &t::ISO8859_15_FROM_UNICODE_TREE,
        )),
        PG_LATIN10 => Some((
            &t::ISO8859_16_TO_UNICODE_TREE,
            &t::ISO8859_16_FROM_UNICODE_TREE,
        )),
        PG_ISO_8859_5 => Some((
            &t::ISO8859_5_TO_UNICODE_TREE,
            &t::ISO8859_5_FROM_UNICODE_TREE,
        )),
        PG_ISO_8859_6 => Some((
            &t::ISO8859_6_TO_UNICODE_TREE,
            &t::ISO8859_6_FROM_UNICODE_TREE,
        )),
        PG_ISO_8859_7 => Some((
            &t::ISO8859_7_TO_UNICODE_TREE,
            &t::ISO8859_7_FROM_UNICODE_TREE,
        )),
        PG_ISO_8859_8 => Some((
            &t::ISO8859_8_TO_UNICODE_TREE,
            &t::ISO8859_8_FROM_UNICODE_TREE,
        )),
        _ => None,
    }
}

const WIN_FAMILY: [pg_enc; 11] = [
    PG_WIN866, PG_WIN874, PG_WIN1250, PG_WIN1251, PG_WIN1252, PG_WIN1253, PG_WIN1254, PG_WIN1255,
    PG_WIN1256, PG_WIN1257, PG_WIN1258,
];

const ISO8859_FAMILY: [pg_enc; 13] = [
    PG_LATIN2,
    PG_LATIN3,
    PG_LATIN4,
    PG_LATIN5,
    PG_LATIN6,
    PG_LATIN7,
    PG_LATIN8,
    PG_LATIN9,
    PG_LATIN10,
    PG_ISO_8859_5,
    PG_ISO_8859_6,
    PG_ISO_8859_7,
    PG_ISO_8859_8,
];

#[track_caller]
#[cold]
fn unexpected_encoding(encoding: pg_enc, family: &str) -> Box<PgError> {
    Box::new(
        PgError::error(format!(
            "unexpected encoding ID {encoding} for {family} character sets"
        ))
        .with_sqlstate(ERRCODE_INTERNAL_ERROR),
    )
}

fn family_maps(
    encoding: pg_enc,
    family: &'static [pg_enc],
    family_name: &'static str,
    lookup: fn(pg_enc) -> Option<(&'static PgMbRadixTree, &'static PgMbRadixTree)>,
) -> PgResult<(&'static PgMbRadixTree, &'static PgMbRadixTree)> {
    debug_assert!(lookup(encoding).is_none() || family.contains(&encoding));
    match lookup(encoding) {
        Some(maps) => Ok(maps),
        None => Err(unexpected_encoding(encoding, family_name)),
    }
}

pub fn fc_win_to_utf8(_flinfo: Option<&mut FmgrInfo>, fcinfo: &mut Fcinfo) -> PgResult<Datum> {
    let a = unsafe { ConvArgs::from(fcinfo) };
    check_encoding_conversion_args(a.src_encoding, a.dest_encoding, a.len, -1, PG_UTF8)?;
    let (to_utf8, _) = family_maps(a.src_encoding, &WIN_FAMILY, "WIN", win_maps)?;
    let n = unsafe {
        LocalToUtf(
            a.src(),
            a.dest,
            to_utf8,
            &[],
            None,
            a.src_encoding,
            a.no_error,
        )?
    };
    Ok(Datum::from_i32(n))
}

pub fn fc_utf8_to_win(_flinfo: Option<&mut FmgrInfo>, fcinfo: &mut Fcinfo) -> PgResult<Datum> {
    let a = unsafe { ConvArgs::from(fcinfo) };
    check_encoding_conversion_args(a.src_encoding, a.dest_encoding, a.len, PG_UTF8, -1)?;
    let (_, from_utf8) = family_maps(a.dest_encoding, &WIN_FAMILY, "WIN", win_maps)?;
    let n = unsafe {
        UtfToLocal(
            a.src(),
            a.dest,
            from_utf8,
            &[],
            None,
            a.dest_encoding,
            a.no_error,
        )?
    };
    Ok(Datum::from_i32(n))
}

pub fn fc_iso8859_to_utf8(_flinfo: Option<&mut FmgrInfo>, fcinfo: &mut Fcinfo) -> PgResult<Datum> {
    let a = unsafe { ConvArgs::from(fcinfo) };
    check_encoding_conversion_args(a.src_encoding, a.dest_encoding, a.len, -1, PG_UTF8)?;
    let (to_utf8, _) = family_maps(a.src_encoding, &ISO8859_FAMILY, "ISO 8859", iso8859_maps)?;
    let n = unsafe {
        LocalToUtf(
            a.src(),
            a.dest,
            to_utf8,
            &[],
            None,
            a.src_encoding,
            a.no_error,
        )?
    };
    Ok(Datum::from_i32(n))
}

pub fn fc_utf8_to_iso8859(_flinfo: Option<&mut FmgrInfo>, fcinfo: &mut Fcinfo) -> PgResult<Datum> {
    let a = unsafe { ConvArgs::from(fcinfo) };
    check_encoding_conversion_args(a.src_encoding, a.dest_encoding, a.len, PG_UTF8, -1)?;
    let (_, from_utf8) = family_maps(a.dest_encoding, &ISO8859_FAMILY, "ISO 8859", iso8859_maps)?;
    let n = unsafe {
        UtfToLocal(
            a.src(),
            a.dest,
            from_utf8,
            &[],
            None,
            a.dest_encoding,
            a.no_error,
        )?
    };
    Ok(Datum::from_i32(n))
}

// pg_proc rows for these are prolang 'c' (not in fmgrtab/CANONICAL); OIDs
// verified against pg_proc.dat 18.3. Strictly OID-ascending.
pub const CONV_BUILTINS: &[FmgrBuiltin] = &[
    FmgrBuiltin {
        foid: 4302,
        name: "koi8r_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_koi8r_to_mic,
    },
    FmgrBuiltin {
        foid: 4303,
        name: "mic_to_koi8r",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_mic_to_koi8r,
    },
    FmgrBuiltin {
        foid: 4304,
        name: "iso_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_iso_to_mic,
    },
    FmgrBuiltin {
        foid: 4305,
        name: "mic_to_iso",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_mic_to_iso,
    },
    FmgrBuiltin {
        foid: 4306,
        name: "win1251_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win1251_to_mic,
    },
    FmgrBuiltin {
        foid: 4307,
        name: "mic_to_win1251",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_mic_to_win1251,
    },
    FmgrBuiltin {
        foid: 4308,
        name: "win866_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win866_to_mic,
    },
    FmgrBuiltin {
        foid: 4309,
        name: "mic_to_win866",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_mic_to_win866,
    },
    FmgrBuiltin {
        foid: 4310,
        name: "koi8r_to_win1251",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_koi8r_to_win1251,
    },
    FmgrBuiltin {
        foid: 4311,
        name: "win1251_to_koi8r",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win1251_to_koi8r,
    },
    FmgrBuiltin {
        foid: 4312,
        name: "koi8r_to_win866",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_koi8r_to_win866,
    },
    FmgrBuiltin {
        foid: 4313,
        name: "win866_to_koi8r",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win866_to_koi8r,
    },
    FmgrBuiltin {
        foid: 4314,
        name: "win866_to_win1251",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win866_to_win1251,
    },
    FmgrBuiltin {
        foid: 4315,
        name: "win1251_to_win866",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win1251_to_win866,
    },
    FmgrBuiltin {
        foid: 4316,
        name: "iso_to_koi8r",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_iso_to_koi8r,
    },
    FmgrBuiltin {
        foid: 4317,
        name: "koi8r_to_iso",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_koi8r_to_iso,
    },
    FmgrBuiltin {
        foid: 4318,
        name: "iso_to_win1251",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_iso_to_win1251,
    },
    FmgrBuiltin {
        foid: 4319,
        name: "win1251_to_iso",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win1251_to_iso,
    },
    FmgrBuiltin {
        foid: 4320,
        name: "iso_to_win866",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_iso_to_win866,
    },
    FmgrBuiltin {
        foid: 4321,
        name: "win866_to_iso",
        nargs: 6,
        strict: true,
        retset: false,
        func: cyrillic_and_mic::fc_win866_to_iso,
    },
    FmgrBuiltin {
        foid: 4322,
        name: "euc_cn_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_cn_and_mic::fc_euc_cn_to_mic,
    },
    FmgrBuiltin {
        foid: 4323,
        name: "mic_to_euc_cn",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_cn_and_mic::fc_mic_to_euc_cn,
    },
    FmgrBuiltin {
        foid: 4324,
        name: "euc_jp_to_sjis",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_jp_and_sjis::fc_euc_jp_to_sjis,
    },
    FmgrBuiltin {
        foid: 4325,
        name: "sjis_to_euc_jp",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_jp_and_sjis::fc_sjis_to_euc_jp,
    },
    FmgrBuiltin {
        foid: 4326,
        name: "euc_jp_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_jp_and_sjis::fc_euc_jp_to_mic,
    },
    FmgrBuiltin {
        foid: 4327,
        name: "sjis_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_jp_and_sjis::fc_sjis_to_mic,
    },
    FmgrBuiltin {
        foid: 4328,
        name: "mic_to_euc_jp",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_jp_and_sjis::fc_mic_to_euc_jp,
    },
    FmgrBuiltin {
        foid: 4329,
        name: "mic_to_sjis",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_jp_and_sjis::fc_mic_to_sjis,
    },
    FmgrBuiltin {
        foid: 4330,
        name: "euc_kr_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_kr_and_mic::fc_euc_kr_to_mic,
    },
    FmgrBuiltin {
        foid: 4331,
        name: "mic_to_euc_kr",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_kr_and_mic::fc_mic_to_euc_kr,
    },
    FmgrBuiltin {
        foid: 4332,
        name: "euc_tw_to_big5",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_tw_and_big5::fc_euc_tw_to_big5,
    },
    FmgrBuiltin {
        foid: 4333,
        name: "big5_to_euc_tw",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_tw_and_big5::fc_big5_to_euc_tw,
    },
    FmgrBuiltin {
        foid: 4334,
        name: "euc_tw_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_tw_and_big5::fc_euc_tw_to_mic,
    },
    FmgrBuiltin {
        foid: 4335,
        name: "big5_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_tw_and_big5::fc_big5_to_mic,
    },
    FmgrBuiltin {
        foid: 4336,
        name: "mic_to_euc_tw",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_tw_and_big5::fc_mic_to_euc_tw,
    },
    FmgrBuiltin {
        foid: 4337,
        name: "mic_to_big5",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc_tw_and_big5::fc_mic_to_big5,
    },
    FmgrBuiltin {
        foid: 4338,
        name: "latin2_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin2_and_win1250::fc_latin2_to_mic,
    },
    FmgrBuiltin {
        foid: 4339,
        name: "mic_to_latin2",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin2_and_win1250::fc_mic_to_latin2,
    },
    FmgrBuiltin {
        foid: 4340,
        name: "win1250_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin2_and_win1250::fc_win1250_to_mic,
    },
    FmgrBuiltin {
        foid: 4341,
        name: "mic_to_win1250",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin2_and_win1250::fc_mic_to_win1250,
    },
    FmgrBuiltin {
        foid: 4342,
        name: "latin2_to_win1250",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin2_and_win1250::fc_latin2_to_win1250,
    },
    FmgrBuiltin {
        foid: 4343,
        name: "win1250_to_latin2",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin2_and_win1250::fc_win1250_to_latin2,
    },
    FmgrBuiltin {
        foid: 4344,
        name: "latin1_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin_and_mic::fc_latin1_to_mic,
    },
    FmgrBuiltin {
        foid: 4345,
        name: "mic_to_latin1",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin_and_mic::fc_mic_to_latin1,
    },
    FmgrBuiltin {
        foid: 4346,
        name: "latin3_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin_and_mic::fc_latin3_to_mic,
    },
    FmgrBuiltin {
        foid: 4347,
        name: "mic_to_latin3",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin_and_mic::fc_mic_to_latin3,
    },
    FmgrBuiltin {
        foid: 4348,
        name: "latin4_to_mic",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin_and_mic::fc_latin4_to_mic,
    },
    FmgrBuiltin {
        foid: 4349,
        name: "mic_to_latin4",
        nargs: 6,
        strict: true,
        retset: false,
        func: latin_and_mic::fc_mic_to_latin4,
    },
    FmgrBuiltin {
        foid: 4352,
        name: "big5_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_big5_to_utf8,
    },
    FmgrBuiltin {
        foid: 4353,
        name: "utf8_to_big5",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_big5,
    },
    FmgrBuiltin {
        foid: 4354,
        name: "utf8_to_koi8r",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_koi8r,
    },
    FmgrBuiltin {
        foid: 4355,
        name: "koi8r_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_koi8r_to_utf8,
    },
    FmgrBuiltin {
        foid: 4356,
        name: "utf8_to_koi8u",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_koi8u,
    },
    FmgrBuiltin {
        foid: 4357,
        name: "koi8u_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_koi8u_to_utf8,
    },
    FmgrBuiltin {
        foid: 4358,
        name: "utf8_to_win",
        nargs: 6,
        strict: true,
        retset: false,
        func: fc_utf8_to_win,
    },
    FmgrBuiltin {
        foid: 4359,
        name: "win_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: fc_win_to_utf8,
    },
    FmgrBuiltin {
        foid: 4360,
        name: "euc_cn_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_euc_cn_to_utf8,
    },
    FmgrBuiltin {
        foid: 4361,
        name: "utf8_to_euc_cn",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_euc_cn,
    },
    FmgrBuiltin {
        foid: 4362,
        name: "euc_jp_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_euc_jp_to_utf8,
    },
    FmgrBuiltin {
        foid: 4363,
        name: "utf8_to_euc_jp",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_euc_jp,
    },
    FmgrBuiltin {
        foid: 4364,
        name: "euc_kr_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_euc_kr_to_utf8,
    },
    FmgrBuiltin {
        foid: 4365,
        name: "utf8_to_euc_kr",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_euc_kr,
    },
    FmgrBuiltin {
        foid: 4366,
        name: "euc_tw_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_euc_tw_to_utf8,
    },
    FmgrBuiltin {
        foid: 4367,
        name: "utf8_to_euc_tw",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_euc_tw,
    },
    FmgrBuiltin {
        foid: 4368,
        name: "gb18030_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_gb18030_to_utf8,
    },
    FmgrBuiltin {
        foid: 4369,
        name: "utf8_to_gb18030",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_gb18030,
    },
    FmgrBuiltin {
        foid: 4370,
        name: "gbk_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_gbk_to_utf8,
    },
    FmgrBuiltin {
        foid: 4371,
        name: "utf8_to_gbk",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_gbk,
    },
    FmgrBuiltin {
        foid: 4372,
        name: "utf8_to_iso8859",
        nargs: 6,
        strict: true,
        retset: false,
        func: fc_utf8_to_iso8859,
    },
    FmgrBuiltin {
        foid: 4373,
        name: "iso8859_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: fc_iso8859_to_utf8,
    },
    FmgrBuiltin {
        foid: 4374,
        name: "iso8859_1_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: fc_iso8859_1_to_utf8,
    },
    FmgrBuiltin {
        foid: 4375,
        name: "utf8_to_iso8859_1",
        nargs: 6,
        strict: true,
        retset: false,
        func: fc_utf8_to_iso8859_1,
    },
    FmgrBuiltin {
        foid: 4376,
        name: "johab_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_johab_to_utf8,
    },
    FmgrBuiltin {
        foid: 4377,
        name: "utf8_to_johab",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_johab,
    },
    FmgrBuiltin {
        foid: 4378,
        name: "sjis_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_sjis_to_utf8,
    },
    FmgrBuiltin {
        foid: 4379,
        name: "utf8_to_sjis",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_sjis,
    },
    FmgrBuiltin {
        foid: 4380,
        name: "uhc_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_uhc_to_utf8,
    },
    FmgrBuiltin {
        foid: 4381,
        name: "utf8_to_uhc",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_uhc,
    },
    FmgrBuiltin {
        foid: 4382,
        name: "euc_jis_2004_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_euc_jis_2004_to_utf8,
    },
    FmgrBuiltin {
        foid: 4383,
        name: "utf8_to_euc_jis_2004",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_euc_jis_2004,
    },
    FmgrBuiltin {
        foid: 4384,
        name: "shift_jis_2004_to_utf8",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_shift_jis_2004_to_utf8,
    },
    FmgrBuiltin {
        foid: 4385,
        name: "utf8_to_shift_jis_2004",
        nargs: 6,
        strict: true,
        retset: false,
        func: utf8_procs::fc_utf8_to_shift_jis_2004,
    },
    FmgrBuiltin {
        foid: 4386,
        name: "euc_jis_2004_to_shift_jis_2004",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc2004_sjis2004::fc_euc_jis_2004_to_shift_jis_2004,
    },
    FmgrBuiltin {
        foid: 4387,
        name: "shift_jis_2004_to_euc_jis_2004",
        nargs: 6,
        strict: true,
        retset: false,
        func: euc2004_sjis2004::fc_shift_jis_2004_to_euc_jis_2004,
    },
];

pub fn conv_builtin(oid: Oid) -> Option<&'static FmgrBuiltin> {
    CONV_BUILTINS
        .binary_search_by_key(&oid, |b| b.foid)
        .ok()
        .map(|i| &CONV_BUILTINS[i])
}

/// `appendStringInfoStringQuoted` (stringinfo_mb.c): appends `s` single-quoted
/// with embedded quotes doubled, clipped to `maxlen` bytes (mb-aware, `maxlen
/// < 0` means unclipped) with a trailing ellipsis when truncated.
pub fn append_string_info_string_quoted(
    buf: &mut mcx::PgString<'_>,
    s: &str,
    maxlen: i32,
) -> PgResult<()> {
    let slen = s.len() as i32;
    let (s, ellipsis) = if maxlen >= 0 && maxlen < slen {
        (
            &s[..mbutils::pg_mbcliplen(s.as_bytes(), slen, maxlen) as usize],
            true,
        )
    } else {
        (s, false)
    };
    buf.try_push('\'')?;
    let mut first = true;
    for chunk in s.split('\'') {
        if !first {
            buf.try_push_str("''")?;
        }
        buf.try_push_str(chunk)?;
        first = false;
    }
    buf.try_push_str(if ellipsis { "...'" } else { "'" })
}

#[cfg(test)]
mod tests;
