//! Oracle vectors generated by compiling blutils.c myRand/mySrand/signValue verbatim.

use crate::*;

#[test]
fn meta_layout_constants_match_c() {
    assert_eq!(BLOOM_OPTIONS_SIZE, 136);
    assert_eq!(BLOOM_META_BLOCK_N, 2004);
    assert_eq!(BLOOM_META_DATA_SIZE, 8160);
    assert_eq!(PAGE_CONTENTS_OFF + BLOOM_META_DATA_SIZE, OPAQUE_OFF);
    assert_eq!(OPAQUE_OFF, 8184);
    assert_eq!(MAX_BLOOM_LENGTH, 4096);
    assert_eq!(MAX_BLOOM_BITS, 4095);
}

#[test]
fn default_options_match_c() {
    let opts = BloomOptions::default();
    assert_eq!(opts.bloom_length, 5); // 80 bits -> 5 words
    assert!(opts.bit_size.iter().all(|&b| b == 2));
    assert_eq!(opts.size_of_bloom_tuple(), 6 + 10);
}

#[test]
fn options_roundtrip_and_varlena_header() {
    let mut opts = BloomOptions::default();
    opts.bloom_length = 7;
    opts.bit_size[3] = 11;
    let mut buf = [0u8; BLOOM_OPTIONS_SIZE];
    opts.write(&mut buf);
    assert_eq!(u32::from_ne_bytes(buf[0..4].try_into().unwrap()), 136 << 2);
    assert_eq!(BloomOptions::read(&buf), opts);
}

#[test]
fn myrand_stream_matches_c_oracle() {
    // (seed, first 5 myRand() values) from the C oracle, incl. wrap seeds.
    let oracle: &[(u32, [i32; 5])] = &[
        (0, [16806, 282475248, 1622650072, 984943657, 1144108929]),
        (1, [33613, 564950497, 1097816498, 1969887315, 140734212]),
        (42, [722700, 1409017471, 1054476434, 1550388000, 1952043755]),
        (
            0x7fffffff,
            [33613, 564950497, 1097816498, 1969887315, 140734212],
        ),
        (
            0x80000000,
            [2147466839, 1865008397, 524833573, 1162539988, 1003374716],
        ),
        (
            0xdeadbeef,
            [1624403319, 386994928, 1643288586, 2111581288, 31973900],
        ),
        (0xffffffff, [-1, -1, -1, -1, -1]),
    ];
    for &(seed, expect) in oracle {
        let mut rng = BlRng::new(seed);
        let got: Vec<i32> = (0..5).map(|_| rng.next()).collect();
        assert_eq!(got, expect, "seed {seed}");
    }
}

#[test]
fn sign_value_matches_c_oracle() {
    // (attno, hash, bit_size, len_words, expected signature words) from C.
    struct Case {
        attno: usize,
        hash: u32,
        bits: i32,
        len: i32,
        expect: &'static [u16],
    }
    let cases = [
        Case {
            attno: 0,
            hash: 0x12345678,
            bits: 2,
            len: 5,
            expect: &[0, 0, 16392, 0, 0],
        },
        Case {
            attno: 1,
            hash: 0x12345678,
            bits: 2,
            len: 5,
            expect: &[4, 0, 0, 32768, 0],
        },
        Case {
            attno: 0,
            hash: 0,
            bits: 2,
            len: 5,
            expect: &[0, 0, 0, 1, 256],
        },
        Case {
            attno: 1,
            hash: 0xffffffff,
            bits: 3,
            len: 5,
            expect: &[8, 0, 8, 0, 4096],
        },
        Case {
            attno: 0,
            hash: 0xcafebabe,
            bits: 4,
            len: 1,
            expect: &[17440],
        },
    ];
    for c in &cases {
        let mut sign = vec![0u16; c.len as usize];
        add_value_bits(&mut sign, c.attno, c.hash, c.bits, c.len);
        assert_eq!(sign, c.expect, "attno={} hash={}", c.attno, c.hash);
    }
    let mut sign = vec![0u16; 256];
    add_value_bits(&mut sign, 31, 0x01020304, 2, 256);
    let set: Vec<(usize, u16)> = sign
        .iter()
        .enumerate()
        .filter(|(_, &w)| w != 0)
        .map(|(i, &w)| (i, w))
        .collect();
    assert_eq!(set, vec![(42, 64), (208, 2048)]);
}

#[test]
fn stuck_rng_setbit_is_a_noop_not_a_panic() {
    // attno such that hash ^ first-draw == 0xffffffff puts the generator in
    // the stuck -1 state; SETBIT(sign, -1) must be C's masked-shift no-op.
    let mut rng = BlRng::new(0);
    let first = rng.next() as u32;
    let hash = 0xffffffffu32 ^ first;
    let mut sign = vec![0u16; 5];
    add_value_bits(&mut sign, 0, hash, 4, 5);
    assert_eq!(sign, vec![0, 0, 0, 0, 0]);
}

#[test]
fn page_init_add_item_free_space() {
    let opts = BloomOptions::default();
    let sz = opts.size_of_bloom_tuple(); // 16
    let mut page = vec![0u8; types_core::BLCKSZ];
    assert!(page_is_new(&page));
    bloom_init_page(&mut page, 0);
    assert!(!page_is_new(&page));
    assert!(!page_is_meta(&page));
    assert!(!page_is_deleted(&page));
    assert_eq!(opaque_maxoff(&page), 0);
    assert_eq!(pd_lower(&page), 24);
    assert_eq!(pd_upper(&page), OPAQUE_OFF as u16);
    assert_eq!(
        u16::from_ne_bytes([page[OPAQUE_OFF + 6], page[OPAQUE_OFF + 7]]),
        BLOOM_PAGE_ID
    );

    let capacity = (types_core::BLCKSZ - 24 - 8) / sz; // 510 tuples at default opts
    assert_eq!(capacity, 510);
    let tuple = vec![0xABu8; sz];
    for i in 0..capacity {
        assert!(page_add_item(&mut page, sz, &tuple), "tuple {i}");
    }
    assert!(!page_add_item(&mut page, sz, &tuple), "page must be full");
    assert_eq!(opaque_maxoff(&page) as usize, capacity);
    assert_eq!(pd_lower(&page) as usize, 24 + capacity * sz);
    assert!(page_free_space(sz, opaque_maxoff(&page)) < sz as isize);

    page_set_deleted(&mut page);
    assert!(page_is_deleted(&page));
}

#[test]
fn metapage_fill_and_accessors() {
    let mut page = vec![0u8; types_core::BLCKSZ];
    bloom_init_page(&mut page, BLOOM_META);
    let mut opts = BloomOptions::default();
    opts.bloom_length = 7;
    fill_metapage(&mut page, &opts);
    assert!(page_is_meta(&page));
    assert_eq!(meta_magick(&page), BLOOM_MAGICK_NUMBER);
    assert_eq!(meta_nstart(&page), 0);
    assert_eq!(meta_nend(&page), 0);
    assert_eq!(meta_opts(&page), opts);
    assert_eq!(pd_lower(&page) as usize, 24 + BLOOM_META_DATA_SIZE);
    assert_eq!(pd_lower(&page), pd_upper(&page));

    meta_set_nstart(&mut page, 3);
    meta_set_nend(&mut page, 9);
    meta_set_notfull(&mut page, 0, 17);
    meta_set_notfull(&mut page, BLOOM_META_BLOCK_N - 1, 99);
    assert_eq!(meta_nstart(&page), 3);
    assert_eq!(meta_nend(&page), 9);
    assert_eq!(meta_notfull(&page, 0), 17);
    assert_eq!(meta_notfull(&page, BLOOM_META_BLOCK_N - 1), 99);
}

#[test]
fn signature_containment() {
    let stored: Vec<u8> = [0b1010u16, 0xffff, 0]
        .iter()
        .flat_map(|w| w.to_ne_bytes())
        .collect();
    assert!(signature_matches(&stored, &[0b1010, 0x0f0f, 0]));
    assert!(signature_matches(&stored, &[0, 0, 0]));
    assert!(!signature_matches(&stored, &[0b0100, 0, 0]));
    assert!(!signature_matches(&stored, &[0, 0, 1]));
}
