//! Fixture-backed unit battery: positive decode against pyarrow-generated
//! fixtures (testdata/, regenerated by scripts/gen-parquet-fixtures.py) and
//! the fuzz-shaped corrupt-footer battery (truncations + deterministic byte
//! flips must yield typed errors, never panics).

use crate::{ColumnBatch, FileReader};

fn fixture(name: &str) -> String {
    format!("{}/testdata/{name}", env!("CARGO_MANIFEST_DIR"))
}

/// Decode every row of every column with odd batch sizes (page-crossing);
/// returns (reader, decoded row count).
fn read_all(path: &str) -> (FileReader, usize) {
    let mut r = FileReader::open(path).expect("open");
    let ncols = r.meta.columns.len();
    let cols: Vec<usize> = (0..ncols).collect();
    let vutf8: Vec<bool> = vec![false; ncols];
    let mut batches: Vec<ColumnBatch> = r
        .meta
        .columns
        .iter()
        .map(|c| ColumnBatch::new_for(c.phys))
        .collect();
    let mut rows = 0usize;
    for rg in 0..r.meta.row_groups.len() {
        let mut rgr = r.row_group(rg, &cols, &vutf8).expect("row group");
        while rgr.rows_remaining() > 0 {
            let n = rgr.rows_remaining().min(521) as usize;
            rgr.read_batches(&mut batches, n).expect("read");
            rows += n;
        }
    }
    (r, rows)
}

// The generator writes rows with these exact generation rules; assertions
// recompute them independently (see scripts/gen-parquet-fixtures.py).
fn expect_i64(i: usize) -> i64 {
    (i as i64).wrapping_mul(2654435761) % 1_000_003
}

#[test]
fn basic_fixture_decodes_exactly() {
    let path = fixture("basic.parquet");
    if !std::path::Path::new(&path).exists() {
        panic!("missing checked-in fixture basic.parquet (run scripts/gen-parquet-fixtures.py)");
    }
    let (r, rows) = read_all(&path);
    assert_eq!(rows as i64, r.meta.num_rows);
    assert!(r.meta.row_groups.len() >= 2, "fixture must span row groups");

    // Re-read with typed assertions on every row of every column.
    let mut fr = FileReader::open(&path).unwrap();
    let ncols = fr.meta.columns.len();
    let names: Vec<String> = fr.meta.columns.iter().map(|c| c.name.clone()).collect();
    let cols: Vec<usize> = (0..ncols).collect();
    let vutf8: Vec<bool> = fr
        .meta
        .columns
        .iter()
        .map(|c| c.phys == crate::Phys::ByteArray)
        .collect();
    let mut batches: Vec<ColumnBatch> = fr
        .meta
        .columns
        .iter()
        .map(|c| ColumnBatch::new_for(c.phys))
        .collect();
    let mut row = 0usize;
    for rg in 0..fr.meta.row_groups.len() {
        let mut rgr = fr.row_group(rg, &cols, &vutf8).unwrap();
        while rgr.rows_remaining() > 0 {
            let n = rgr.rows_remaining().min(333) as usize;
            rgr.read_batches(&mut batches, n).unwrap();
            for k in 0..n {
                let i = row + k;
                for (c, b) in batches.iter().enumerate() {
                    check_cell(&names[c], b, k, i);
                }
            }
            row += n;
        }
    }
}

fn check_cell(name: &str, b: &ColumnBatch, k: usize, i: usize) {
    use crate::BatchData::*;
    match name {
        "id" => {
            let I64(v) = &b.data else { panic!("id type") };
            assert!(!b.is_null(k));
            assert_eq!(v[k], i as i64);
        }
        "i32req" => {
            let I32(v) = &b.data else {
                panic!("i32req type")
            };
            assert_eq!(v[k] as i64, expect_i64(i) % 100_000);
        }
        "i32opt" => {
            let I32(v) = &b.data else {
                panic!("i32opt type")
            };
            if i % 7 == 0 {
                assert!(b.is_null(k), "row {i}");
            } else {
                assert!(!b.is_null(k), "row {i}");
                assert_eq!(v[k] as i64, expect_i64(i) % 32000);
            }
        }
        "i64opt" => {
            let I64(v) = &b.data else {
                panic!("i64opt type")
            };
            if i % 11 == 0 {
                assert!(b.is_null(k));
            } else {
                assert_eq!(v[k], expect_i64(i));
            }
        }
        "f32req" => {
            let F32(v) = &b.data else {
                panic!("f32req type")
            };
            assert_eq!(v[k], (i % 1000) as f32 * 0.5);
        }
        "f64opt" => {
            let F64(v) = &b.data else {
                panic!("f64opt type")
            };
            if i % 13 == 0 {
                assert!(b.is_null(k));
            } else {
                assert_eq!(v[k], (i % 10_000) as f64 * 0.25);
            }
        }
        "breq" => {
            let Bool(v) = &b.data else {
                panic!("breq type")
            };
            assert_eq!(v[k], i % 3 == 0);
        }
        "bopt" => {
            let Bool(v) = &b.data else {
                panic!("bopt type")
            };
            if i % 5 == 0 {
                assert!(b.is_null(k));
            } else {
                assert_eq!(v[k], i % 2 == 0);
            }
        }
        "dict" => {
            assert!(!b.is_null(k));
            assert_eq!(b.bytes_at(k), format!("key-{:04}", i % 101).as_bytes());
        }
        "uniq" => {
            assert_eq!(b.bytes_at(k), format!("uniq-{i:09}").as_bytes());
        }
        "sopt" => {
            if i % 3 == 0 {
                assert!(b.is_null(k));
                assert_eq!(b.bytes_at(k), b"");
            } else {
                assert_eq!(b.bytes_at(k), format!("s{}", i % 17).as_bytes());
            }
        }
        "d" => {
            let I32(v) = &b.data else { panic!("d type") };
            assert_eq!(v[k], 19000 + (i % 400) as i32); // days since Unix epoch
        }
        "ts" => {
            let I64(v) = &b.data else { panic!("ts type") };
            assert_eq!(v[k], 1_700_000_000_000_000i64 + (i as i64) * 1_000_003);
        }
        other => panic!("unexpected column {other}"),
    }
}

#[test]
fn empty_and_allnull_fixtures() {
    let (r, rows) = read_all(&fixture("empty.parquet"));
    assert_eq!(rows, 0);
    assert_eq!(r.meta.num_rows, 0);

    let (r, rows) = read_all(&fixture("allnulls.parquet"));
    assert_eq!(rows as i64, r.meta.num_rows);
}

#[test]
fn codec_fixtures_roundtrip() {
    for f in ["zstd.parquet", "lz4raw.parquet", "uncompressed.parquet"] {
        let path = fixture(f);
        let (r, rows) = read_all(&path);
        assert_eq!(rows as i64, r.meta.num_rows, "{f}");
        assert!(rows > 0, "{f}");
    }
}

#[test]
fn dict_plain_fallback_fixture() {
    // Written with a tiny dictionary-size cap: the wide column flips from
    // dictionary pages to PLAIN mid-chunk; values must still be exact.
    let path = fixture("dictfallback.parquet");
    let mut fr = FileReader::open(&path).unwrap();
    let ncols = fr.meta.columns.len();
    let cols: Vec<usize> = (0..ncols).collect();
    let vutf8 = vec![true; ncols];
    let mut batches: Vec<ColumnBatch> = fr
        .meta
        .columns
        .iter()
        .map(|c| ColumnBatch::new_for(c.phys))
        .collect();
    let mut row = 0usize;
    for rg in 0..fr.meta.row_groups.len() {
        let mut rgr = fr.row_group(rg, &cols, &vutf8).unwrap();
        while rgr.rows_remaining() > 0 {
            let n = rgr.rows_remaining().min(701) as usize;
            rgr.read_batches(&mut batches, n).unwrap();
            for k in 0..n {
                let i = row + k;
                assert_eq!(
                    batches[0].bytes_at(k),
                    format!("wide-{i:06}-{}", "x".repeat(40)).as_bytes()
                );
            }
            row += n;
        }
    }
    assert_eq!(row as i64, fr.meta.num_rows);
}

#[test]
fn unsupported_features_error_cleanly() {
    for (f, needle) in [
        ("v2pages.parquet", "data page v2"),
        ("nested.parquet", "nested"),
        ("gzip.parquet", "GZIP"),
        ("int96.parquet", "INT96"),
        ("delta.parquet", "DELTA_BINARY_PACKED"),
    ] {
        let path = fixture(f);
        let r = FileReader::open(&path);
        let err = match r {
            Err(e) => format!("{e:?}"),
            Ok(mut fr) => {
                // Schema-level features error at open; page-level ones at
                // first decode.
                let ncols = fr.meta.columns.len();
                let cols: Vec<usize> = (0..ncols).collect();
                let vutf8 = vec![false; ncols];
                let mut batches: Vec<ColumnBatch> = fr
                    .meta
                    .columns
                    .iter()
                    .map(|c| ColumnBatch::new_for(c.phys))
                    .collect();
                let mut got = None;
                'outer: for rg in 0..fr.meta.row_groups.len() {
                    let mut rgr = match fr.row_group(rg, &cols, &vutf8) {
                        Ok(r) => r,
                        Err(e) => {
                            got = Some(format!("{e:?}"));
                            break;
                        }
                    };
                    while rgr.rows_remaining() > 0 {
                        let n = rgr.rows_remaining().min(512) as usize;
                        if let Err(e) = rgr.read_batches(&mut batches, n) {
                            got = Some(format!("{e:?}"));
                            break 'outer;
                        }
                    }
                }
                got.unwrap_or_else(|| panic!("{f}: expected a clean error"))
            }
        };
        assert!(err.contains(needle), "{f}: error {err:?} lacks {needle:?}");
    }
}

#[test]
fn invalid_utf8_detected_in_binary_column() {
    // badutf8.parquet stores invalid UTF-8 in a BYTE_ARRAY (binary) column;
    // reading with validate_utf8 must error, without it must succeed.
    let path = fixture("badutf8.parquet");
    let mut fr = FileReader::open(&path).unwrap();
    let cols = vec![0usize];
    let mut batches = vec![ColumnBatch::new_for(fr.meta.columns[0].phys)];
    let mut rgr = fr.row_group(0, &cols, &[false]).unwrap();
    let n = rgr.rows_remaining() as usize;
    rgr.read_batches(&mut batches, n).expect("raw read");

    let mut fr = FileReader::open(&path).unwrap();
    let mut rgr = fr.row_group(0, &cols, &[true]).unwrap();
    let n = rgr.rows_remaining() as usize;
    let err = rgr.read_batches(&mut batches, n).expect_err("must reject");
    assert!(format!("{err:?}").contains("UTF8"), "{err:?}");
}

// ---- fuzz-shaped negative battery ------------------------------------------

#[test]
fn truncations_never_panic() {
    let path = fixture("basic.parquet");
    let bytes = std::fs::read(&path).unwrap();
    let dir = std::env::temp_dir().join(format!("pqread-trunc-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    // Truncate at a spread of positions, dense near the footer.
    let mut cuts: Vec<usize> = (0..bytes.len()).step_by(977).collect();
    for i in bytes.len().saturating_sub(64)..bytes.len() {
        cuts.push(i);
    }
    for (n, cut) in cuts.into_iter().enumerate() {
        let p = dir.join(format!("t{n}.parquet"));
        std::fs::write(&p, &bytes[..cut]).unwrap();
        let ps = p.to_str().unwrap();
        // Must not panic: any Err (or a short read caught later) is fine.
        if let Ok(mut fr) = FileReader::open(ps) {
            let ncols = fr.meta.columns.len();
            let cols: Vec<usize> = (0..ncols).collect();
            let vutf8 = vec![false; ncols];
            let mut batches: Vec<ColumnBatch> = fr
                .meta
                .columns
                .iter()
                .map(|c| ColumnBatch::new_for(c.phys))
                .collect();
            for rg in 0..fr.meta.row_groups.len() {
                let Ok(mut rgr) = fr.row_group(rg, &cols, &vutf8) else {
                    break;
                };
                while rgr.rows_remaining() > 0 {
                    let n = rgr.rows_remaining().min(512) as usize;
                    if rgr.read_batches(&mut batches, n).is_err() {
                        break;
                    }
                }
            }
        }
        std::fs::remove_file(&p).ok();
    }
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn footer_byte_flips_never_panic() {
    let path = fixture("basic.parquet");
    let bytes = std::fs::read(&path).unwrap();
    let footer_len =
        u32::from_le_bytes(bytes[bytes.len() - 8..bytes.len() - 4].try_into().unwrap()) as usize;
    let footer_start = bytes.len() - 8 - footer_len;
    let dir = std::env::temp_dir().join(format!("pqread-flip-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    // Deterministic xorshift over flip positions/values: every footer byte
    // region gets hit; decode must never panic.
    let mut x: u64 = 0x243F6A8885A308D3;
    for n in 0..600 {
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        let pos = footer_start + (x as usize % (footer_len + 8));
        let val = (x >> 32) as u8;
        let mut m = bytes.clone();
        let at = pos.min(m.len() - 1);
        m[at] ^= val | 1;
        let p = dir.join(format!("f{n}.parquet"));
        std::fs::write(&p, &m).unwrap();
        let ps = p.to_str().unwrap();
        if let Ok(mut fr) = FileReader::open(ps) {
            let ncols = fr.meta.columns.len();
            let cols: Vec<usize> = (0..ncols).collect();
            let vutf8 = vec![false; ncols];
            let mut batches: Vec<ColumnBatch> = fr
                .meta
                .columns
                .iter()
                .map(|c| ColumnBatch::new_for(c.phys))
                .collect();
            for rg in 0..fr.meta.row_groups.len() {
                let Ok(mut rgr) = fr.row_group(rg, &cols, &vutf8) else {
                    break;
                };
                while rgr.rows_remaining() > 0 {
                    let n = rgr.rows_remaining().min(512) as usize;
                    if rgr.read_batches(&mut batches, n).is_err() {
                        break;
                    }
                }
            }
        }
        std::fs::remove_file(&p).ok();
    }
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn page_byte_flips_never_panic() {
    // Flip bytes in the page region (before the footer): decoding must
    // either succeed (bit flip inside value payload) or error - no panics,
    // no runaway allocations.
    let path = fixture("uncompressed.parquet");
    let bytes = std::fs::read(&path).unwrap();
    let footer_len =
        u32::from_le_bytes(bytes[bytes.len() - 8..bytes.len() - 4].try_into().unwrap()) as usize;
    let footer_start = bytes.len() - 8 - footer_len;
    let dir = std::env::temp_dir().join(format!("pqread-pflip-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let mut x: u64 = 0x13198A2E03707344;
    for n in 0..400 {
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        let pos = 4 + (x as usize % footer_start.saturating_sub(4).max(1));
        let mut m = bytes.clone();
        m[pos] ^= ((x >> 32) as u8) | 1;
        let p = dir.join(format!("p{n}.parquet"));
        std::fs::write(&p, &m).unwrap();
        let ps = p.to_str().unwrap();
        if let Ok(mut fr) = FileReader::open(ps) {
            let ncols = fr.meta.columns.len();
            let cols: Vec<usize> = (0..ncols).collect();
            let vutf8 = vec![false; ncols];
            let mut batches: Vec<ColumnBatch> = fr
                .meta
                .columns
                .iter()
                .map(|c| ColumnBatch::new_for(c.phys))
                .collect();
            for rg in 0..fr.meta.row_groups.len() {
                let Ok(mut rgr) = fr.row_group(rg, &cols, &vutf8) else {
                    break;
                };
                while rgr.rows_remaining() > 0 {
                    let k = rgr.rows_remaining().min(512) as usize;
                    if rgr.read_batches(&mut batches, k).is_err() {
                        break;
                    }
                }
            }
        }
        std::fs::remove_file(&p).ok();
    }
    std::fs::remove_dir_all(&dir).ok();
}

/// Corpus sweep (apache/parquet-testing): every file must either decode or
/// yield a typed error — never a panic. Run explicitly:
///   PQ_CORPUS=/path/to/parquet-testing cargo test -p parquet_read \
///       --release -- --ignored corpus_never_panics --nocapture
#[test]
#[ignore = "needs PQ_CORPUS pointing at an apache/parquet-testing clone"]
fn corpus_never_panics() {
    let Ok(root) = std::env::var("PQ_CORPUS") else {
        panic!("set PQ_CORPUS to an apache/parquet-testing checkout");
    };
    let mut files: Vec<std::path::PathBuf> = Vec::new();
    for sub in ["data", "bad_data"] {
        let dir = std::path::Path::new(&root).join(sub);
        let Ok(rd) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "parquet") {
                files.push(p);
            }
        }
    }
    assert!(!files.is_empty(), "no corpus files under {root}");
    files.sort();
    let (mut full, mut open_err, mut decode_err) = (0usize, 0usize, 0usize);
    for p in &files {
        let ps = p.to_str().unwrap();
        let name = p.file_name().unwrap().to_string_lossy();
        match FileReader::open(ps) {
            Err(e) => {
                open_err += 1;
                println!("OPEN-ERR  {name}: {}", e.message);
            }
            Ok(mut fr) => {
                let ncols = fr.meta.columns.len();
                let cols: Vec<usize> = (0..ncols).collect();
                let vutf8 = vec![false; ncols];
                let mut batches: Vec<ColumnBatch> = fr
                    .meta
                    .columns
                    .iter()
                    .map(|c| ColumnBatch::new_for(c.phys))
                    .collect();
                let mut failed = None;
                'rgs: for rg in 0..fr.meta.row_groups.len() {
                    let mut rgr = match fr.row_group(rg, &cols, &vutf8) {
                        Ok(r) => r,
                        Err(e) => {
                            failed = Some(e);
                            break;
                        }
                    };
                    while rgr.rows_remaining() > 0 {
                        let n = rgr.rows_remaining().min(1024) as usize;
                        if let Err(e) = rgr.read_batches(&mut batches, n) {
                            failed = Some(e);
                            break 'rgs;
                        }
                    }
                }
                match failed {
                    None => {
                        full += 1;
                        println!("DECODED   {name} ({} rows)", fr.meta.num_rows);
                    }
                    Some(e) => {
                        decode_err += 1;
                        println!("DEC-ERR   {name}: {}", e.message);
                    }
                }
            }
        }
    }
    println!("corpus: {full} decoded, {open_err} open-errors, {decode_err} decode-errors");
}

/// Footer-inspection harness: PQ_FOOTER points at a raw footer byte file
/// (optionally with the 8 trailing length+magic bytes); prints the schema.
#[test]
#[ignore = "needs PQ_FOOTER pointing at raw footer bytes"]
fn dump_footer_schema() {
    let path = std::env::var("PQ_FOOTER").expect("set PQ_FOOTER");
    let mut b = std::fs::read(&path).unwrap();
    if b.len() > 8 && &b[b.len() - 4..] == b"PAR1" {
        let fl = u32::from_le_bytes(b[b.len() - 8..b.len() - 4].try_into().unwrap()) as usize;
        assert!(fl <= b.len() - 8);
        let start = b.len() - 8 - fl;
        b.drain(..start);
        b.truncate(fl);
    }
    let meta = crate::parse_footer_bytes(&b).expect("parse");
    println!(
        "rows={} rgs={} cols={} created_by={:?}",
        meta.num_rows,
        meta.row_groups.len(),
        meta.columns.len(),
        meta.created_by
    );
    for (i, c) in meta.columns.iter().enumerate() {
        println!(
            "{i:3} {} {} maxdef={} {:?}",
            c.name,
            c.phys.name(),
            c.max_def,
            c.logical
        );
    }
    let mut codecs = std::collections::BTreeMap::new();
    for rg in &meta.row_groups {
        for ch in &rg.chunks {
            *codecs.entry(ch.codec.name()).or_insert(0u64) += 1;
        }
    }
    println!("codecs: {codecs:?}");
}
