//! print.c debug printers. Formatting is byte-exact vs C (oracle fixtures in
//! cprint_expected.txt, regenerated by scripts/print-oracle-e2e.sh); the dump
//! source is outfuncs::nodeToString, which renders every location as -1
//! (C print.c uses nodeToStringWithLocations).
use core::fmt::Write;

use mcx::{Mcx, PgString};
use types_core::AttrNumber;
use types_error::{ErrorLevel, ErrorLocation, PgResult};
use types_nodes::parsenodes::{RTEKind, RangeTblEntry};
use types_nodes::primnodes::{INDEX_VAR, INNER_VAR, OUTER_VAR};
use types_nodes::{Node, NodeList, NodeTag};

const LINELEN: usize = 78;
const INDENTSTOP: i32 = 3;
const MAXINDENT: i32 = 60;

fn line_str(line: &[u8]) -> &str {
    core::str::from_utf8(line).expect("node dump is ASCII")
}

fn emit(out: &mut PgString<'_>, line: &[u8]) {
    push(out, line_str(line));
    push(out, "\n");
}

fn push(out: &mut PgString<'_>, s: &str) {
    out.try_push_str(s).expect("print append");
}

pub fn format_node_dump<'mcx>(mcx: Mcx<'mcx>, dump: &str) -> PgResult<PgString<'mcx>> {
    let d = dump.as_bytes();
    let mut line = [0u8; LINELEN + 1];
    let mut out = PgString::new_in(mcx);
    let mut i = 0usize;
    let mut j;
    loop {
        j = 0;
        while j < LINELEN && i < d.len() {
            line[j] = d[i];
            i += 1;
            j += 1;
        }
        if i >= d.len() {
            break;
        }
        if d[i] == b' ' {
            i += 1;
        } else {
            let mut k = j as i32 - 1;
            while k > 0 && line[k as usize] != b' ' {
                k -= 1;
            }
            if k > 0 {
                i -= j - k as usize - 1;
                j = k as usize;
            }
        }
        emit(&mut out, &line[..j]);
    }
    if j > 0 {
        emit(&mut out, &line[..j]);
    }
    Ok(out)
}

pub fn pretty_format_node_dump<'mcx>(mcx: Mcx<'mcx>, dump: &str) -> PgResult<PgString<'mcx>> {
    let d = dump.as_bytes();
    let mut line = [0u8; LINELEN + 1];
    let mut out = PgString::new_in(mcx);
    let mut indent_lev: i32 = 0;
    let mut indent_dist: i32 = 0;
    let mut i = 0usize;
    let mut j: i32;
    loop {
        j = 0;
        while j < indent_dist {
            line[j as usize] = b' ';
            j += 1;
        }
        while j < LINELEN as i32 && i < d.len() {
            line[j as usize] = d[i];
            match line[j as usize] {
                b'}' => {
                    if j != indent_dist {
                        emit(&mut out, &line[..j as usize]);
                    }
                    line[indent_dist as usize] = b'}';
                    emit(&mut out, &line[..indent_dist as usize + 1]);
                    if indent_lev > 0 {
                        indent_lev -= 1;
                        indent_dist = (indent_lev * INDENTSTOP).min(MAXINDENT);
                    }
                    j = indent_dist - 1;
                    while i + 1 < d.len() && d[i + 1] == b' ' {
                        i += 1;
                    }
                }
                b')' => {
                    if i + 1 >= d.len() || d[i + 1] != b')' {
                        emit(&mut out, &line[..j as usize + 1]);
                        j = indent_dist - 1;
                        while i + 1 < d.len() && d[i + 1] == b' ' {
                            i += 1;
                        }
                    }
                }
                b'{' => {
                    if j != indent_dist {
                        emit(&mut out, &line[..j as usize]);
                    }
                    indent_lev += 1;
                    indent_dist = (indent_lev * INDENTSTOP).min(MAXINDENT);
                    j = 0;
                    while j < indent_dist {
                        line[j as usize] = b' ';
                        j += 1;
                    }
                    line[j as usize] = d[i];
                }
                b':' => {
                    if j != indent_dist {
                        emit(&mut out, &line[..j as usize]);
                    }
                    j = indent_dist;
                    line[j as usize] = d[i];
                }
                _ => {}
            }
            i += 1;
            j += 1;
        }
        if i >= d.len() {
            break;
        }
        emit(&mut out, &line[..j as usize]);
    }
    if j > 0 {
        emit(&mut out, &line[..j as usize]);
    }
    Ok(out)
}

pub fn print(mcx: Mcx<'_>, node: Node<'_>) -> PgResult<()> {
    let s = outfuncs::nodeToString(mcx, node)?;
    let f = format_node_dump(mcx, s.as_str())?;
    stdout_line(f.as_str());
    Ok(())
}

pub fn pprint(mcx: Mcx<'_>, node: Node<'_>) -> PgResult<()> {
    let s = outfuncs::nodeToString(mcx, node)?;
    let f = pretty_format_node_dump(mcx, s.as_str())?;
    stdout_line(f.as_str());
    Ok(())
}

fn stdout_line(s: &str) {
    use std::io::Write as _;
    let mut o = std::io::stdout();
    let _ = o.write_all(s.as_bytes());
    let _ = o.write_all(b"\n");
    let _ = o.flush();
}

pub fn elog_node_display(
    mcx: Mcx<'_>,
    lev: ErrorLevel,
    title: &str,
    node: Node<'_>,
    pretty: bool,
) -> PgResult<()> {
    let s = outfuncs::nodeToString(mcx, node)?;
    let f = if pretty {
        pretty_format_node_dump(mcx, s.as_str())?
    } else {
        format_node_dump(mcx, s.as_str())?
    };
    elog::ereport(lev)
        .errmsg_internal(format!("{title}:"))
        .errdetail_internal(f.as_str().to_owned())
        .finish(ErrorLocation::new(
            file!(),
            line!() as i32,
            "elog_node_display",
        ))
}

pub fn print_rt(mcx: Mcx<'_>, rtable: &NodeList<'_>) {
    let mut buf = PgString::new_in(mcx);
    write_rt(&mut buf, rtable);
    stdout_flush(buf.as_str());
}

fn write_rt(buf: &mut PgString<'_>, rtable: &NodeList<'_>) {
    let _ = writeln!(buf, "resno\trefname  \trelid\tinFromCl");
    let _ = writeln!(buf, "-----\t---------\t-----\t--------");
    for (idx, rte_node) in rtable.iter().enumerate() {
        let i = idx + 1;
        let rte = rte_node.as_range_tbl_entry().expect("rtable element");
        let aliasname = rte.eref.and_then(|e| e.aliasname).unwrap_or("");
        let _ = match rte.rtekind {
            RTEKind::RTE_RELATION => {
                write!(
                    buf,
                    "{i}\t{aliasname}\t{}\t{}",
                    rte.relid, rte.relkind as char
                )
            }
            RTEKind::RTE_SUBQUERY => write!(buf, "{i}\t{aliasname}\t[subquery]"),
            RTEKind::RTE_JOIN => write!(buf, "{i}\t{aliasname}\t[join]"),
            RTEKind::RTE_FUNCTION => write!(buf, "{i}\t{aliasname}\t[rangefunction]"),
            RTEKind::RTE_TABLEFUNC => write!(buf, "{i}\t{aliasname}\t[table function]"),
            RTEKind::RTE_VALUES => write!(buf, "{i}\t{aliasname}\t[values list]"),
            RTEKind::RTE_CTE => write!(buf, "{i}\t{aliasname}\t[cte]"),
            RTEKind::RTE_NAMEDTUPLESTORE => write!(buf, "{i}\t{aliasname}\t[tuplestore]"),
            RTEKind::RTE_RESULT => write!(buf, "{i}\t{aliasname}\t[result]"),
            RTEKind::RTE_GROUP => write!(buf, "{i}\t{aliasname}\t[group]"),
        };
        let _ = writeln!(
            buf,
            "\t{}\t{}",
            if rte.inh { "inh" } else { "" },
            if rte.inFromCl { "inFromCl" } else { "" }
        );
    }
}

fn stdout_flush(s: &str) {
    use std::io::Write as _;
    let mut o = std::io::stdout();
    let _ = o.write_all(s.as_bytes());
    let _ = o.flush();
}

// parse_relation.c get_rte_attribute_name (print_expr's only consumer here).
fn rte_attribute_name<'mcx>(
    mcx: Mcx<'mcx>,
    rte: &RangeTblEntry<'mcx>,
    attnum: AttrNumber,
) -> PgResult<PgString<'mcx>> {
    if attnum == 0 {
        return PgString::from_str_in("*", mcx);
    }
    let colname = |alias: &types_nodes::primnodes::Alias<'mcx>| -> Option<&'mcx str> {
        if attnum > 0 && (attnum as usize) <= alias.colnames.len() {
            alias
                .colnames
                .nth(attnum as usize - 1)
                .as_string()
                .map(|s| s.sval)
        } else {
            None
        }
    };
    if let Some(name) = rte.alias.and_then(colname) {
        return PgString::from_str_in(name, mcx);
    }
    if rte.rtekind == RTEKind::RTE_RELATION {
        return Ok(lsyscache::get_attname(mcx, rte.relid, attnum, false)?
            .expect("get_attname missing_ok=false"));
    }
    if let Some(name) = rte.eref.and_then(colname) {
        return PgString::from_str_in(name, mcx);
    }
    panic!(
        "invalid attnum {attnum} for rangetable entry {}",
        rte.eref.and_then(|e| e.aliasname).unwrap_or("")
    );
}

fn output_function_call<'mcx>(
    mcx: Mcx<'mcx>,
    typoutput: types_core::Oid,
    value: datum::Datum,
) -> PgResult<PgString<'mcx>> {
    let mut finfo = fmgr_seams::fmgr_info::call(typoutput)?;
    let d = types_fmgr::function_call1_coll_in(&mut finfo, types_core::InvalidOid, mcx, value)?;
    // SAFETY: out functions return a NUL-terminated cstring datum; copied out
    // before finfo (and its scratch) dies.
    let s = unsafe { core::ffi::CStr::from_ptr(d.as_usize() as *const core::ffi::c_char) };
    PgString::from_str_in(s.to_str().expect("output fn result is UTF-8"), mcx)
}

pub fn print_expr(mcx: Mcx<'_>, expr: Option<Node<'_>>, rtable: &NodeList<'_>) -> PgResult<()> {
    let mut buf = PgString::new_in(mcx);
    write_expr(&mut buf, mcx, expr, rtable)?;
    stdout_flush(buf.as_str());
    Ok(())
}

fn write_expr(
    buf: &mut PgString<'_>,
    mcx: Mcx<'_>,
    expr: Option<Node<'_>>,
    rtable: &NodeList<'_>,
) -> PgResult<()> {
    let Some(expr) = expr else {
        push(buf, "<>");
        return Ok(());
    };
    match expr.node_tag() {
        NodeTag::T_Var => {
            let var = expr.as_var().unwrap();
            match var.varno {
                INNER_VAR => push(buf, "INNER.?"),
                OUTER_VAR => push(buf, "OUTER.?"),
                INDEX_VAR => push(buf, "INDEX.?"),
                _ => {
                    debug_assert!(var.varno > 0 && var.varno as usize <= rtable.len());
                    let rte = rtable
                        .nth(var.varno as usize - 1)
                        .as_range_tbl_entry()
                        .expect("rtable element");
                    let relname = rte.eref.and_then(|e| e.aliasname).unwrap_or("");
                    let attname = rte_attribute_name(mcx, rte, var.varattno)?;
                    let _ = write!(buf, "{relname}.{}", attname.as_str());
                }
            }
        }
        NodeTag::T_Const => {
            let c = expr.as_const().unwrap();
            if c.constisnull {
                push(buf, "NULL");
                return Ok(());
            }
            let (typoutput, _) = lsyscache::getTypeOutputInfo(c.consttype)?;
            let s = output_function_call(mcx, typoutput, c.constvalue)?;
            push(buf, s.as_str());
        }
        NodeTag::T_OpExpr => {
            let e = expr.as_op_expr().unwrap();
            let opname = lsyscache::operator::get_opname(mcx, e.opno)?;
            let opname = opname
                .as_ref()
                .map(|s| s.as_str())
                .unwrap_or("(invalid operator)");
            if e.args.len() > 1 {
                write_expr(buf, mcx, Some(e.args.nth(0)), rtable)?;
                let _ = write!(buf, " {opname} ");
                write_expr(buf, mcx, Some(e.args.nth(1)), rtable)?;
            } else {
                let _ = write!(buf, "{opname} ");
                write_expr(buf, mcx, Some(e.args.nth(0)), rtable)?;
            }
        }
        NodeTag::T_FuncExpr => {
            let e = expr.as_func_expr().unwrap();
            let funcname = lsyscache::get_func_name(mcx, e.funcid)?;
            let funcname = funcname
                .as_ref()
                .map(|s| s.as_str())
                .unwrap_or("(invalid function)");
            let _ = write!(buf, "{funcname}(");
            for (i, arg) in e.args.iter().enumerate() {
                write_expr(buf, mcx, Some(arg), rtable)?;
                if i + 1 < e.args.len() {
                    push(buf, ",");
                }
            }
            push(buf, ")");
        }
        _ => push(buf, "unknown expr"),
    }
    Ok(())
}

pub fn print_tl(mcx: Mcx<'_>, tlist: &NodeList<'_>, rtable: &NodeList<'_>) -> PgResult<()> {
    let mut buf = PgString::new_in(mcx);
    push(&mut buf, "(\n");
    for tl in tlist {
        let tle = tl.as_target_entry().expect("tlist element");
        let _ = write!(buf, "\t{} {}\t", tle.resno, tle.resname.unwrap_or("<null>"));
        if tle.ressortgroupref != 0 {
            let _ = write!(buf, "({}):\t", tle.ressortgroupref);
        } else {
            push(&mut buf, "    :\t");
        }
        write_expr(&mut buf, mcx, Some(tle.expr), rtable)?;
        push(&mut buf, "\n");
    }
    push(&mut buf, ")\n");
    stdout_flush(buf.as_str());
    Ok(())
}

pub fn print_pathkeys() -> ! {
    panic!(
        "print.c print_pathkeys unported: pathnodes here are PlannerInfo arena \
         handles, not a List walkable from nodes_core — planner-debug lane"
    )
}

pub fn print_slot() -> ! {
    panic!("print.c print_slot unported: debugtup (printtup.c) has no port — printer lane")
}
