// datetktbl/deltatktbl from datetime.c: generated, dual-extraction diff-verified.
// Strictly alphabetical (datebsearch requirement); checked by tests.
use crate::consts::*;

const fn tk(token: &[u8], typ: i32, value: i32) -> DateTkn {
    let mut t = [0u8; TOKMAXLEN + 1];
    let mut i = 0;
    while i < token.len() {
        t[i] = token[i];
        i += 1;
    }
    DateTkn {
        token: t,
        typ: typ as i8,
        value,
    }
}

pub static DATETKTBL: [DateTkn; 72] = [
    tk(b"+infinity", RESERV, DTK_LATE),
    tk(b"-infinity", RESERV, DTK_EARLY),
    tk(b"ad", ADBC, 0),
    tk(b"allballs", RESERV, DTK_ZULU),
    tk(b"am", AMPM, 0),
    tk(b"apr", MONTH, 4),
    tk(b"april", MONTH, 4),
    tk(b"at", IGNORE_DTF, 0),
    tk(b"aug", MONTH, 8),
    tk(b"august", MONTH, 8),
    tk(b"bc", ADBC, 1),
    tk(b"d", UNITS, DTK_DAY),
    tk(b"dec", MONTH, 12),
    tk(b"december", MONTH, 12),
    tk(b"dow", UNITS, DTK_DOW),
    tk(b"doy", UNITS, DTK_DOY),
    tk(b"dst", DTZMOD, SECS_PER_HOUR),
    tk(b"epoch", RESERV, DTK_EPOCH),
    tk(b"feb", MONTH, 2),
    tk(b"february", MONTH, 2),
    tk(b"fri", DOW, 5),
    tk(b"friday", DOW, 5),
    tk(b"h", UNITS, DTK_HOUR),
    tk(b"infinity", RESERV, DTK_LATE),
    tk(b"isodow", UNITS, DTK_ISODOW),
    tk(b"isoyear", UNITS, DTK_ISOYEAR),
    tk(b"j", UNITS, DTK_JULIAN),
    tk(b"jan", MONTH, 1),
    tk(b"january", MONTH, 1),
    tk(b"jd", UNITS, DTK_JULIAN),
    tk(b"jul", MONTH, 7),
    tk(b"julian", UNITS, DTK_JULIAN),
    tk(b"july", MONTH, 7),
    tk(b"jun", MONTH, 6),
    tk(b"june", MONTH, 6),
    tk(b"m", UNITS, DTK_MONTH),
    tk(b"mar", MONTH, 3),
    tk(b"march", MONTH, 3),
    tk(b"may", MONTH, 5),
    tk(b"mm", UNITS, DTK_MINUTE),
    tk(b"mon", DOW, 1),
    tk(b"monday", DOW, 1),
    tk(b"nov", MONTH, 11),
    tk(b"november", MONTH, 11),
    tk(b"now", RESERV, DTK_NOW),
    tk(b"oct", MONTH, 10),
    tk(b"october", MONTH, 10),
    tk(b"on", IGNORE_DTF, 0),
    tk(b"pm", AMPM, 1),
    tk(b"s", UNITS, DTK_SECOND),
    tk(b"sat", DOW, 6),
    tk(b"saturday", DOW, 6),
    tk(b"sep", MONTH, 9),
    tk(b"sept", MONTH, 9),
    tk(b"september", MONTH, 9),
    tk(b"sun", DOW, 0),
    tk(b"sunday", DOW, 0),
    tk(b"t", ISOTIME, DTK_TIME),
    tk(b"thu", DOW, 4),
    tk(b"thur", DOW, 4),
    tk(b"thurs", DOW, 4),
    tk(b"thursday", DOW, 4),
    tk(b"today", RESERV, DTK_TODAY),
    tk(b"tomorrow", RESERV, DTK_TOMORROW),
    tk(b"tue", DOW, 2),
    tk(b"tues", DOW, 2),
    tk(b"tuesday", DOW, 2),
    tk(b"wed", DOW, 3),
    tk(b"wednesday", DOW, 3),
    tk(b"weds", DOW, 3),
    tk(b"y", UNITS, DTK_YEAR),
    tk(b"yesterday", RESERV, DTK_YESTERDAY),
];

pub static DELTATKTBL: [DateTkn; 61] = [
    tk(b"@", IGNORE_DTF, 0),
    tk(b"ago", AGO, 0),
    tk(b"c", UNITS, DTK_CENTURY),
    tk(b"cent", UNITS, DTK_CENTURY),
    tk(b"centuries", UNITS, DTK_CENTURY),
    tk(b"century", UNITS, DTK_CENTURY),
    tk(b"d", UNITS, DTK_DAY),
    tk(b"day", UNITS, DTK_DAY),
    tk(b"days", UNITS, DTK_DAY),
    tk(b"dec", UNITS, DTK_DECADE),
    tk(b"decade", UNITS, DTK_DECADE),
    tk(b"decades", UNITS, DTK_DECADE),
    tk(b"decs", UNITS, DTK_DECADE),
    tk(b"h", UNITS, DTK_HOUR),
    tk(b"hour", UNITS, DTK_HOUR),
    tk(b"hours", UNITS, DTK_HOUR),
    tk(b"hr", UNITS, DTK_HOUR),
    tk(b"hrs", UNITS, DTK_HOUR),
    tk(b"m", UNITS, DTK_MINUTE),
    tk(b"microsecon", UNITS, DTK_MICROSEC),
    tk(b"mil", UNITS, DTK_MILLENNIUM),
    tk(b"millennia", UNITS, DTK_MILLENNIUM),
    tk(b"millennium", UNITS, DTK_MILLENNIUM),
    tk(b"millisecon", UNITS, DTK_MILLISEC),
    tk(b"mils", UNITS, DTK_MILLENNIUM),
    tk(b"min", UNITS, DTK_MINUTE),
    tk(b"mins", UNITS, DTK_MINUTE),
    tk(b"minute", UNITS, DTK_MINUTE),
    tk(b"minutes", UNITS, DTK_MINUTE),
    tk(b"mon", UNITS, DTK_MONTH),
    tk(b"mons", UNITS, DTK_MONTH),
    tk(b"month", UNITS, DTK_MONTH),
    tk(b"months", UNITS, DTK_MONTH),
    tk(b"ms", UNITS, DTK_MILLISEC),
    tk(b"msec", UNITS, DTK_MILLISEC),
    tk(b"msecond", UNITS, DTK_MILLISEC),
    tk(b"mseconds", UNITS, DTK_MILLISEC),
    tk(b"msecs", UNITS, DTK_MILLISEC),
    tk(b"qtr", UNITS, DTK_QUARTER),
    tk(b"quarter", UNITS, DTK_QUARTER),
    tk(b"s", UNITS, DTK_SECOND),
    tk(b"sec", UNITS, DTK_SECOND),
    tk(b"second", UNITS, DTK_SECOND),
    tk(b"seconds", UNITS, DTK_SECOND),
    tk(b"secs", UNITS, DTK_SECOND),
    tk(b"timezone", UNITS, DTK_TZ),
    tk(b"timezone_h", UNITS, DTK_TZ_HOUR),
    tk(b"timezone_m", UNITS, DTK_TZ_MINUTE),
    tk(b"us", UNITS, DTK_MICROSEC),
    tk(b"usec", UNITS, DTK_MICROSEC),
    tk(b"usecond", UNITS, DTK_MICROSEC),
    tk(b"useconds", UNITS, DTK_MICROSEC),
    tk(b"usecs", UNITS, DTK_MICROSEC),
    tk(b"w", UNITS, DTK_WEEK),
    tk(b"week", UNITS, DTK_WEEK),
    tk(b"weeks", UNITS, DTK_WEEK),
    tk(b"y", UNITS, DTK_YEAR),
    tk(b"year", UNITS, DTK_YEAR),
    tk(b"years", UNITS, DTK_YEAR),
    tk(b"yr", UNITS, DTK_YEAR),
    tk(b"yrs", UNITS, DTK_YEAR),
];
