// CommandTag values are positional indices in tcop/cmdtaglist.h (PG 18.3);
// every constant is pinned against the cmdtag crate table in tests.
use types_core::CommandTag;

pub const CMDTAG_UNKNOWN: CommandTag = CommandTag(0);
pub const CMDTAG_ALTER_ACCESS_METHOD: CommandTag = CommandTag(1);
pub const CMDTAG_ALTER_AGGREGATE: CommandTag = CommandTag(2);
pub const CMDTAG_ALTER_CAST: CommandTag = CommandTag(3);
pub const CMDTAG_ALTER_COLLATION: CommandTag = CommandTag(4);
pub const CMDTAG_ALTER_CONSTRAINT: CommandTag = CommandTag(5);
pub const CMDTAG_ALTER_CONVERSION: CommandTag = CommandTag(6);
pub const CMDTAG_ALTER_DATABASE: CommandTag = CommandTag(7);
pub const CMDTAG_ALTER_DEFAULT_PRIVILEGES: CommandTag = CommandTag(8);
pub const CMDTAG_ALTER_DOMAIN: CommandTag = CommandTag(9);
pub const CMDTAG_ALTER_EVENT_TRIGGER: CommandTag = CommandTag(10);
pub const CMDTAG_ALTER_EXTENSION: CommandTag = CommandTag(11);
pub const CMDTAG_ALTER_FOREIGN_DATA_WRAPPER: CommandTag = CommandTag(12);
pub const CMDTAG_ALTER_FOREIGN_TABLE: CommandTag = CommandTag(13);
pub const CMDTAG_ALTER_FUNCTION: CommandTag = CommandTag(14);
pub const CMDTAG_ALTER_INDEX: CommandTag = CommandTag(15);
pub const CMDTAG_ALTER_LANGUAGE: CommandTag = CommandTag(16);
pub const CMDTAG_ALTER_LARGE_OBJECT: CommandTag = CommandTag(17);
pub const CMDTAG_ALTER_MATERIALIZED_VIEW: CommandTag = CommandTag(18);
pub const CMDTAG_ALTER_OPERATOR: CommandTag = CommandTag(19);
pub const CMDTAG_ALTER_OPERATOR_CLASS: CommandTag = CommandTag(20);
pub const CMDTAG_ALTER_OPERATOR_FAMILY: CommandTag = CommandTag(21);
pub const CMDTAG_ALTER_POLICY: CommandTag = CommandTag(22);
pub const CMDTAG_ALTER_PROCEDURE: CommandTag = CommandTag(23);
pub const CMDTAG_ALTER_PUBLICATION: CommandTag = CommandTag(24);
pub const CMDTAG_ALTER_ROLE: CommandTag = CommandTag(25);
pub const CMDTAG_ALTER_ROUTINE: CommandTag = CommandTag(26);
pub const CMDTAG_ALTER_RULE: CommandTag = CommandTag(27);
pub const CMDTAG_ALTER_SCHEMA: CommandTag = CommandTag(28);
pub const CMDTAG_ALTER_SEQUENCE: CommandTag = CommandTag(29);
pub const CMDTAG_ALTER_SERVER: CommandTag = CommandTag(30);
pub const CMDTAG_ALTER_STATISTICS: CommandTag = CommandTag(31);
pub const CMDTAG_ALTER_SUBSCRIPTION: CommandTag = CommandTag(32);
pub const CMDTAG_ALTER_SYSTEM: CommandTag = CommandTag(33);
pub const CMDTAG_ALTER_TABLE: CommandTag = CommandTag(34);
pub const CMDTAG_ALTER_TABLESPACE: CommandTag = CommandTag(35);
pub const CMDTAG_ALTER_TEXT_SEARCH_CONFIGURATION: CommandTag = CommandTag(36);
pub const CMDTAG_ALTER_TEXT_SEARCH_DICTIONARY: CommandTag = CommandTag(37);
pub const CMDTAG_ALTER_TEXT_SEARCH_PARSER: CommandTag = CommandTag(38);
pub const CMDTAG_ALTER_TEXT_SEARCH_TEMPLATE: CommandTag = CommandTag(39);
pub const CMDTAG_ALTER_TRANSFORM: CommandTag = CommandTag(40);
pub const CMDTAG_ALTER_TRIGGER: CommandTag = CommandTag(41);
pub const CMDTAG_ALTER_TYPE: CommandTag = CommandTag(42);
pub const CMDTAG_ALTER_USER_MAPPING: CommandTag = CommandTag(43);
pub const CMDTAG_ALTER_VIEW: CommandTag = CommandTag(44);
pub const CMDTAG_ANALYZE: CommandTag = CommandTag(45);
pub const CMDTAG_BEGIN: CommandTag = CommandTag(46);
pub const CMDTAG_CALL: CommandTag = CommandTag(47);
pub const CMDTAG_CHECKPOINT: CommandTag = CommandTag(48);
pub const CMDTAG_CLOSE: CommandTag = CommandTag(49);
pub const CMDTAG_CLOSE_CURSOR: CommandTag = CommandTag(50);
pub const CMDTAG_CLOSE_CURSOR_ALL: CommandTag = CommandTag(51);
pub const CMDTAG_CLUSTER: CommandTag = CommandTag(52);
pub const CMDTAG_COMMENT: CommandTag = CommandTag(53);
pub const CMDTAG_COMMIT: CommandTag = CommandTag(54);
pub const CMDTAG_COMMIT_PREPARED: CommandTag = CommandTag(55);
pub const CMDTAG_COPY: CommandTag = CommandTag(56);
pub const CMDTAG_COPY_FROM: CommandTag = CommandTag(57);
pub const CMDTAG_CREATE_ACCESS_METHOD: CommandTag = CommandTag(58);
pub const CMDTAG_CREATE_AGGREGATE: CommandTag = CommandTag(59);
pub const CMDTAG_CREATE_CAST: CommandTag = CommandTag(60);
pub const CMDTAG_CREATE_COLLATION: CommandTag = CommandTag(61);
pub const CMDTAG_CREATE_CONSTRAINT: CommandTag = CommandTag(62);
pub const CMDTAG_CREATE_CONVERSION: CommandTag = CommandTag(63);
pub const CMDTAG_CREATE_DATABASE: CommandTag = CommandTag(64);
pub const CMDTAG_CREATE_DOMAIN: CommandTag = CommandTag(65);
pub const CMDTAG_CREATE_EVENT_TRIGGER: CommandTag = CommandTag(66);
pub const CMDTAG_CREATE_EXTENSION: CommandTag = CommandTag(67);
pub const CMDTAG_CREATE_FOREIGN_DATA_WRAPPER: CommandTag = CommandTag(68);
pub const CMDTAG_CREATE_FOREIGN_TABLE: CommandTag = CommandTag(69);
pub const CMDTAG_CREATE_FUNCTION: CommandTag = CommandTag(70);
pub const CMDTAG_CREATE_INDEX: CommandTag = CommandTag(71);
pub const CMDTAG_CREATE_LANGUAGE: CommandTag = CommandTag(72);
pub const CMDTAG_CREATE_MATERIALIZED_VIEW: CommandTag = CommandTag(73);
pub const CMDTAG_CREATE_OPERATOR: CommandTag = CommandTag(74);
pub const CMDTAG_CREATE_OPERATOR_CLASS: CommandTag = CommandTag(75);
pub const CMDTAG_CREATE_OPERATOR_FAMILY: CommandTag = CommandTag(76);
pub const CMDTAG_CREATE_POLICY: CommandTag = CommandTag(77);
pub const CMDTAG_CREATE_PROCEDURE: CommandTag = CommandTag(78);
pub const CMDTAG_CREATE_PUBLICATION: CommandTag = CommandTag(79);
pub const CMDTAG_CREATE_ROLE: CommandTag = CommandTag(80);
pub const CMDTAG_CREATE_ROUTINE: CommandTag = CommandTag(81);
pub const CMDTAG_CREATE_RULE: CommandTag = CommandTag(82);
pub const CMDTAG_CREATE_SCHEMA: CommandTag = CommandTag(83);
pub const CMDTAG_CREATE_SEQUENCE: CommandTag = CommandTag(84);
pub const CMDTAG_CREATE_SERVER: CommandTag = CommandTag(85);
pub const CMDTAG_CREATE_STATISTICS: CommandTag = CommandTag(86);
pub const CMDTAG_CREATE_SUBSCRIPTION: CommandTag = CommandTag(87);
pub const CMDTAG_CREATE_TABLE: CommandTag = CommandTag(88);
pub const CMDTAG_CREATE_TABLE_AS: CommandTag = CommandTag(89);
pub const CMDTAG_CREATE_TABLESPACE: CommandTag = CommandTag(90);
pub const CMDTAG_CREATE_TEXT_SEARCH_CONFIGURATION: CommandTag = CommandTag(91);
pub const CMDTAG_CREATE_TEXT_SEARCH_DICTIONARY: CommandTag = CommandTag(92);
pub const CMDTAG_CREATE_TEXT_SEARCH_PARSER: CommandTag = CommandTag(93);
pub const CMDTAG_CREATE_TEXT_SEARCH_TEMPLATE: CommandTag = CommandTag(94);
pub const CMDTAG_CREATE_TRANSFORM: CommandTag = CommandTag(95);
pub const CMDTAG_CREATE_TRIGGER: CommandTag = CommandTag(96);
pub const CMDTAG_CREATE_TYPE: CommandTag = CommandTag(97);
pub const CMDTAG_CREATE_USER_MAPPING: CommandTag = CommandTag(98);
pub const CMDTAG_CREATE_VIEW: CommandTag = CommandTag(99);
pub const CMDTAG_DEALLOCATE: CommandTag = CommandTag(100);
pub const CMDTAG_DEALLOCATE_ALL: CommandTag = CommandTag(101);
pub const CMDTAG_DECLARE_CURSOR: CommandTag = CommandTag(102);
pub const CMDTAG_DELETE: CommandTag = CommandTag(103);
pub const CMDTAG_DISCARD: CommandTag = CommandTag(104);
pub const CMDTAG_DISCARD_ALL: CommandTag = CommandTag(105);
pub const CMDTAG_DISCARD_PLANS: CommandTag = CommandTag(106);
pub const CMDTAG_DISCARD_SEQUENCES: CommandTag = CommandTag(107);
pub const CMDTAG_DISCARD_TEMP: CommandTag = CommandTag(108);
pub const CMDTAG_DO: CommandTag = CommandTag(109);
pub const CMDTAG_DROP_ACCESS_METHOD: CommandTag = CommandTag(110);
pub const CMDTAG_DROP_AGGREGATE: CommandTag = CommandTag(111);
pub const CMDTAG_DROP_CAST: CommandTag = CommandTag(112);
pub const CMDTAG_DROP_COLLATION: CommandTag = CommandTag(113);
pub const CMDTAG_DROP_CONSTRAINT: CommandTag = CommandTag(114);
pub const CMDTAG_DROP_CONVERSION: CommandTag = CommandTag(115);
pub const CMDTAG_DROP_DATABASE: CommandTag = CommandTag(116);
pub const CMDTAG_DROP_DOMAIN: CommandTag = CommandTag(117);
pub const CMDTAG_DROP_EVENT_TRIGGER: CommandTag = CommandTag(118);
pub const CMDTAG_DROP_EXTENSION: CommandTag = CommandTag(119);
pub const CMDTAG_DROP_FOREIGN_DATA_WRAPPER: CommandTag = CommandTag(120);
pub const CMDTAG_DROP_FOREIGN_TABLE: CommandTag = CommandTag(121);
pub const CMDTAG_DROP_FUNCTION: CommandTag = CommandTag(122);
pub const CMDTAG_DROP_INDEX: CommandTag = CommandTag(123);
pub const CMDTAG_DROP_LANGUAGE: CommandTag = CommandTag(124);
pub const CMDTAG_DROP_MATERIALIZED_VIEW: CommandTag = CommandTag(125);
pub const CMDTAG_DROP_OPERATOR: CommandTag = CommandTag(126);
pub const CMDTAG_DROP_OPERATOR_CLASS: CommandTag = CommandTag(127);
pub const CMDTAG_DROP_OPERATOR_FAMILY: CommandTag = CommandTag(128);
pub const CMDTAG_DROP_OWNED: CommandTag = CommandTag(129);
pub const CMDTAG_DROP_POLICY: CommandTag = CommandTag(130);
pub const CMDTAG_DROP_PROCEDURE: CommandTag = CommandTag(131);
pub const CMDTAG_DROP_PUBLICATION: CommandTag = CommandTag(132);
pub const CMDTAG_DROP_ROLE: CommandTag = CommandTag(133);
pub const CMDTAG_DROP_ROUTINE: CommandTag = CommandTag(134);
pub const CMDTAG_DROP_RULE: CommandTag = CommandTag(135);
pub const CMDTAG_DROP_SCHEMA: CommandTag = CommandTag(136);
pub const CMDTAG_DROP_SEQUENCE: CommandTag = CommandTag(137);
pub const CMDTAG_DROP_SERVER: CommandTag = CommandTag(138);
pub const CMDTAG_DROP_STATISTICS: CommandTag = CommandTag(139);
pub const CMDTAG_DROP_SUBSCRIPTION: CommandTag = CommandTag(140);
pub const CMDTAG_DROP_TABLE: CommandTag = CommandTag(141);
pub const CMDTAG_DROP_TABLESPACE: CommandTag = CommandTag(142);
pub const CMDTAG_DROP_TEXT_SEARCH_CONFIGURATION: CommandTag = CommandTag(143);
pub const CMDTAG_DROP_TEXT_SEARCH_DICTIONARY: CommandTag = CommandTag(144);
pub const CMDTAG_DROP_TEXT_SEARCH_PARSER: CommandTag = CommandTag(145);
pub const CMDTAG_DROP_TEXT_SEARCH_TEMPLATE: CommandTag = CommandTag(146);
pub const CMDTAG_DROP_TRANSFORM: CommandTag = CommandTag(147);
pub const CMDTAG_DROP_TRIGGER: CommandTag = CommandTag(148);
pub const CMDTAG_DROP_TYPE: CommandTag = CommandTag(149);
pub const CMDTAG_DROP_USER_MAPPING: CommandTag = CommandTag(150);
pub const CMDTAG_DROP_VIEW: CommandTag = CommandTag(151);
pub const CMDTAG_EXECUTE: CommandTag = CommandTag(152);
pub const CMDTAG_EXPLAIN: CommandTag = CommandTag(153);
pub const CMDTAG_FETCH: CommandTag = CommandTag(154);
pub const CMDTAG_GRANT: CommandTag = CommandTag(155);
pub const CMDTAG_GRANT_ROLE: CommandTag = CommandTag(156);
pub const CMDTAG_IMPORT_FOREIGN_SCHEMA: CommandTag = CommandTag(157);
pub const CMDTAG_INSERT: CommandTag = CommandTag(158);
pub const CMDTAG_LISTEN: CommandTag = CommandTag(159);
pub const CMDTAG_LOAD: CommandTag = CommandTag(160);
pub const CMDTAG_LOCK_TABLE: CommandTag = CommandTag(161);
pub const CMDTAG_LOGIN: CommandTag = CommandTag(162);
pub const CMDTAG_MERGE: CommandTag = CommandTag(163);
pub const CMDTAG_MOVE: CommandTag = CommandTag(164);
pub const CMDTAG_NOTIFY: CommandTag = CommandTag(165);
pub const CMDTAG_PREPARE: CommandTag = CommandTag(166);
pub const CMDTAG_PREPARE_TRANSACTION: CommandTag = CommandTag(167);
pub const CMDTAG_REASSIGN_OWNED: CommandTag = CommandTag(168);
pub const CMDTAG_REFRESH_MATERIALIZED_VIEW: CommandTag = CommandTag(169);
pub const CMDTAG_REINDEX: CommandTag = CommandTag(170);
pub const CMDTAG_RELEASE: CommandTag = CommandTag(171);
pub const CMDTAG_RESET: CommandTag = CommandTag(172);
pub const CMDTAG_REVOKE: CommandTag = CommandTag(173);
pub const CMDTAG_REVOKE_ROLE: CommandTag = CommandTag(174);
pub const CMDTAG_ROLLBACK: CommandTag = CommandTag(175);
pub const CMDTAG_ROLLBACK_PREPARED: CommandTag = CommandTag(176);
pub const CMDTAG_SAVEPOINT: CommandTag = CommandTag(177);
pub const CMDTAG_SECURITY_LABEL: CommandTag = CommandTag(178);
pub const CMDTAG_SELECT: CommandTag = CommandTag(179);
pub const CMDTAG_SELECT_FOR_KEY_SHARE: CommandTag = CommandTag(180);
pub const CMDTAG_SELECT_FOR_NO_KEY_UPDATE: CommandTag = CommandTag(181);
pub const CMDTAG_SELECT_FOR_SHARE: CommandTag = CommandTag(182);
pub const CMDTAG_SELECT_FOR_UPDATE: CommandTag = CommandTag(183);
pub const CMDTAG_SELECT_INTO: CommandTag = CommandTag(184);
pub const CMDTAG_SET: CommandTag = CommandTag(185);
pub const CMDTAG_SET_CONSTRAINTS: CommandTag = CommandTag(186);
pub const CMDTAG_SHOW: CommandTag = CommandTag(187);
pub const CMDTAG_START_TRANSACTION: CommandTag = CommandTag(188);
pub const CMDTAG_TRUNCATE_TABLE: CommandTag = CommandTag(189);
pub const CMDTAG_UNLISTEN: CommandTag = CommandTag(190);
pub const CMDTAG_UPDATE: CommandTag = CommandTag(191);
pub const CMDTAG_VACUUM: CommandTag = CommandTag(192);

#[cfg(test)]
pub(crate) const CMDTAG_NAMES: &[(CommandTag, &str)] = &[
    (CMDTAG_UNKNOWN, "???"),
    (CMDTAG_ALTER_ACCESS_METHOD, "ALTER ACCESS METHOD"),
    (CMDTAG_ALTER_AGGREGATE, "ALTER AGGREGATE"),
    (CMDTAG_ALTER_CAST, "ALTER CAST"),
    (CMDTAG_ALTER_COLLATION, "ALTER COLLATION"),
    (CMDTAG_ALTER_CONSTRAINT, "ALTER CONSTRAINT"),
    (CMDTAG_ALTER_CONVERSION, "ALTER CONVERSION"),
    (CMDTAG_ALTER_DATABASE, "ALTER DATABASE"),
    (CMDTAG_ALTER_DEFAULT_PRIVILEGES, "ALTER DEFAULT PRIVILEGES"),
    (CMDTAG_ALTER_DOMAIN, "ALTER DOMAIN"),
    (CMDTAG_ALTER_EVENT_TRIGGER, "ALTER EVENT TRIGGER"),
    (CMDTAG_ALTER_EXTENSION, "ALTER EXTENSION"),
    (
        CMDTAG_ALTER_FOREIGN_DATA_WRAPPER,
        "ALTER FOREIGN DATA WRAPPER",
    ),
    (CMDTAG_ALTER_FOREIGN_TABLE, "ALTER FOREIGN TABLE"),
    (CMDTAG_ALTER_FUNCTION, "ALTER FUNCTION"),
    (CMDTAG_ALTER_INDEX, "ALTER INDEX"),
    (CMDTAG_ALTER_LANGUAGE, "ALTER LANGUAGE"),
    (CMDTAG_ALTER_LARGE_OBJECT, "ALTER LARGE OBJECT"),
    (CMDTAG_ALTER_MATERIALIZED_VIEW, "ALTER MATERIALIZED VIEW"),
    (CMDTAG_ALTER_OPERATOR, "ALTER OPERATOR"),
    (CMDTAG_ALTER_OPERATOR_CLASS, "ALTER OPERATOR CLASS"),
    (CMDTAG_ALTER_OPERATOR_FAMILY, "ALTER OPERATOR FAMILY"),
    (CMDTAG_ALTER_POLICY, "ALTER POLICY"),
    (CMDTAG_ALTER_PROCEDURE, "ALTER PROCEDURE"),
    (CMDTAG_ALTER_PUBLICATION, "ALTER PUBLICATION"),
    (CMDTAG_ALTER_ROLE, "ALTER ROLE"),
    (CMDTAG_ALTER_ROUTINE, "ALTER ROUTINE"),
    (CMDTAG_ALTER_RULE, "ALTER RULE"),
    (CMDTAG_ALTER_SCHEMA, "ALTER SCHEMA"),
    (CMDTAG_ALTER_SEQUENCE, "ALTER SEQUENCE"),
    (CMDTAG_ALTER_SERVER, "ALTER SERVER"),
    (CMDTAG_ALTER_STATISTICS, "ALTER STATISTICS"),
    (CMDTAG_ALTER_SUBSCRIPTION, "ALTER SUBSCRIPTION"),
    (CMDTAG_ALTER_SYSTEM, "ALTER SYSTEM"),
    (CMDTAG_ALTER_TABLE, "ALTER TABLE"),
    (CMDTAG_ALTER_TABLESPACE, "ALTER TABLESPACE"),
    (
        CMDTAG_ALTER_TEXT_SEARCH_CONFIGURATION,
        "ALTER TEXT SEARCH CONFIGURATION",
    ),
    (
        CMDTAG_ALTER_TEXT_SEARCH_DICTIONARY,
        "ALTER TEXT SEARCH DICTIONARY",
    ),
    (CMDTAG_ALTER_TEXT_SEARCH_PARSER, "ALTER TEXT SEARCH PARSER"),
    (
        CMDTAG_ALTER_TEXT_SEARCH_TEMPLATE,
        "ALTER TEXT SEARCH TEMPLATE",
    ),
    (CMDTAG_ALTER_TRANSFORM, "ALTER TRANSFORM"),
    (CMDTAG_ALTER_TRIGGER, "ALTER TRIGGER"),
    (CMDTAG_ALTER_TYPE, "ALTER TYPE"),
    (CMDTAG_ALTER_USER_MAPPING, "ALTER USER MAPPING"),
    (CMDTAG_ALTER_VIEW, "ALTER VIEW"),
    (CMDTAG_ANALYZE, "ANALYZE"),
    (CMDTAG_BEGIN, "BEGIN"),
    (CMDTAG_CALL, "CALL"),
    (CMDTAG_CHECKPOINT, "CHECKPOINT"),
    (CMDTAG_CLOSE, "CLOSE"),
    (CMDTAG_CLOSE_CURSOR, "CLOSE CURSOR"),
    (CMDTAG_CLOSE_CURSOR_ALL, "CLOSE CURSOR ALL"),
    (CMDTAG_CLUSTER, "CLUSTER"),
    (CMDTAG_COMMENT, "COMMENT"),
    (CMDTAG_COMMIT, "COMMIT"),
    (CMDTAG_COMMIT_PREPARED, "COMMIT PREPARED"),
    (CMDTAG_COPY, "COPY"),
    (CMDTAG_COPY_FROM, "COPY FROM"),
    (CMDTAG_CREATE_ACCESS_METHOD, "CREATE ACCESS METHOD"),
    (CMDTAG_CREATE_AGGREGATE, "CREATE AGGREGATE"),
    (CMDTAG_CREATE_CAST, "CREATE CAST"),
    (CMDTAG_CREATE_COLLATION, "CREATE COLLATION"),
    (CMDTAG_CREATE_CONSTRAINT, "CREATE CONSTRAINT"),
    (CMDTAG_CREATE_CONVERSION, "CREATE CONVERSION"),
    (CMDTAG_CREATE_DATABASE, "CREATE DATABASE"),
    (CMDTAG_CREATE_DOMAIN, "CREATE DOMAIN"),
    (CMDTAG_CREATE_EVENT_TRIGGER, "CREATE EVENT TRIGGER"),
    (CMDTAG_CREATE_EXTENSION, "CREATE EXTENSION"),
    (
        CMDTAG_CREATE_FOREIGN_DATA_WRAPPER,
        "CREATE FOREIGN DATA WRAPPER",
    ),
    (CMDTAG_CREATE_FOREIGN_TABLE, "CREATE FOREIGN TABLE"),
    (CMDTAG_CREATE_FUNCTION, "CREATE FUNCTION"),
    (CMDTAG_CREATE_INDEX, "CREATE INDEX"),
    (CMDTAG_CREATE_LANGUAGE, "CREATE LANGUAGE"),
    (CMDTAG_CREATE_MATERIALIZED_VIEW, "CREATE MATERIALIZED VIEW"),
    (CMDTAG_CREATE_OPERATOR, "CREATE OPERATOR"),
    (CMDTAG_CREATE_OPERATOR_CLASS, "CREATE OPERATOR CLASS"),
    (CMDTAG_CREATE_OPERATOR_FAMILY, "CREATE OPERATOR FAMILY"),
    (CMDTAG_CREATE_POLICY, "CREATE POLICY"),
    (CMDTAG_CREATE_PROCEDURE, "CREATE PROCEDURE"),
    (CMDTAG_CREATE_PUBLICATION, "CREATE PUBLICATION"),
    (CMDTAG_CREATE_ROLE, "CREATE ROLE"),
    (CMDTAG_CREATE_ROUTINE, "CREATE ROUTINE"),
    (CMDTAG_CREATE_RULE, "CREATE RULE"),
    (CMDTAG_CREATE_SCHEMA, "CREATE SCHEMA"),
    (CMDTAG_CREATE_SEQUENCE, "CREATE SEQUENCE"),
    (CMDTAG_CREATE_SERVER, "CREATE SERVER"),
    (CMDTAG_CREATE_STATISTICS, "CREATE STATISTICS"),
    (CMDTAG_CREATE_SUBSCRIPTION, "CREATE SUBSCRIPTION"),
    (CMDTAG_CREATE_TABLE, "CREATE TABLE"),
    (CMDTAG_CREATE_TABLE_AS, "CREATE TABLE AS"),
    (CMDTAG_CREATE_TABLESPACE, "CREATE TABLESPACE"),
    (
        CMDTAG_CREATE_TEXT_SEARCH_CONFIGURATION,
        "CREATE TEXT SEARCH CONFIGURATION",
    ),
    (
        CMDTAG_CREATE_TEXT_SEARCH_DICTIONARY,
        "CREATE TEXT SEARCH DICTIONARY",
    ),
    (
        CMDTAG_CREATE_TEXT_SEARCH_PARSER,
        "CREATE TEXT SEARCH PARSER",
    ),
    (
        CMDTAG_CREATE_TEXT_SEARCH_TEMPLATE,
        "CREATE TEXT SEARCH TEMPLATE",
    ),
    (CMDTAG_CREATE_TRANSFORM, "CREATE TRANSFORM"),
    (CMDTAG_CREATE_TRIGGER, "CREATE TRIGGER"),
    (CMDTAG_CREATE_TYPE, "CREATE TYPE"),
    (CMDTAG_CREATE_USER_MAPPING, "CREATE USER MAPPING"),
    (CMDTAG_CREATE_VIEW, "CREATE VIEW"),
    (CMDTAG_DEALLOCATE, "DEALLOCATE"),
    (CMDTAG_DEALLOCATE_ALL, "DEALLOCATE ALL"),
    (CMDTAG_DECLARE_CURSOR, "DECLARE CURSOR"),
    (CMDTAG_DELETE, "DELETE"),
    (CMDTAG_DISCARD, "DISCARD"),
    (CMDTAG_DISCARD_ALL, "DISCARD ALL"),
    (CMDTAG_DISCARD_PLANS, "DISCARD PLANS"),
    (CMDTAG_DISCARD_SEQUENCES, "DISCARD SEQUENCES"),
    (CMDTAG_DISCARD_TEMP, "DISCARD TEMP"),
    (CMDTAG_DO, "DO"),
    (CMDTAG_DROP_ACCESS_METHOD, "DROP ACCESS METHOD"),
    (CMDTAG_DROP_AGGREGATE, "DROP AGGREGATE"),
    (CMDTAG_DROP_CAST, "DROP CAST"),
    (CMDTAG_DROP_COLLATION, "DROP COLLATION"),
    (CMDTAG_DROP_CONSTRAINT, "DROP CONSTRAINT"),
    (CMDTAG_DROP_CONVERSION, "DROP CONVERSION"),
    (CMDTAG_DROP_DATABASE, "DROP DATABASE"),
    (CMDTAG_DROP_DOMAIN, "DROP DOMAIN"),
    (CMDTAG_DROP_EVENT_TRIGGER, "DROP EVENT TRIGGER"),
    (CMDTAG_DROP_EXTENSION, "DROP EXTENSION"),
    (
        CMDTAG_DROP_FOREIGN_DATA_WRAPPER,
        "DROP FOREIGN DATA WRAPPER",
    ),
    (CMDTAG_DROP_FOREIGN_TABLE, "DROP FOREIGN TABLE"),
    (CMDTAG_DROP_FUNCTION, "DROP FUNCTION"),
    (CMDTAG_DROP_INDEX, "DROP INDEX"),
    (CMDTAG_DROP_LANGUAGE, "DROP LANGUAGE"),
    (CMDTAG_DROP_MATERIALIZED_VIEW, "DROP MATERIALIZED VIEW"),
    (CMDTAG_DROP_OPERATOR, "DROP OPERATOR"),
    (CMDTAG_DROP_OPERATOR_CLASS, "DROP OPERATOR CLASS"),
    (CMDTAG_DROP_OPERATOR_FAMILY, "DROP OPERATOR FAMILY"),
    (CMDTAG_DROP_OWNED, "DROP OWNED"),
    (CMDTAG_DROP_POLICY, "DROP POLICY"),
    (CMDTAG_DROP_PROCEDURE, "DROP PROCEDURE"),
    (CMDTAG_DROP_PUBLICATION, "DROP PUBLICATION"),
    (CMDTAG_DROP_ROLE, "DROP ROLE"),
    (CMDTAG_DROP_ROUTINE, "DROP ROUTINE"),
    (CMDTAG_DROP_RULE, "DROP RULE"),
    (CMDTAG_DROP_SCHEMA, "DROP SCHEMA"),
    (CMDTAG_DROP_SEQUENCE, "DROP SEQUENCE"),
    (CMDTAG_DROP_SERVER, "DROP SERVER"),
    (CMDTAG_DROP_STATISTICS, "DROP STATISTICS"),
    (CMDTAG_DROP_SUBSCRIPTION, "DROP SUBSCRIPTION"),
    (CMDTAG_DROP_TABLE, "DROP TABLE"),
    (CMDTAG_DROP_TABLESPACE, "DROP TABLESPACE"),
    (
        CMDTAG_DROP_TEXT_SEARCH_CONFIGURATION,
        "DROP TEXT SEARCH CONFIGURATION",
    ),
    (
        CMDTAG_DROP_TEXT_SEARCH_DICTIONARY,
        "DROP TEXT SEARCH DICTIONARY",
    ),
    (CMDTAG_DROP_TEXT_SEARCH_PARSER, "DROP TEXT SEARCH PARSER"),
    (
        CMDTAG_DROP_TEXT_SEARCH_TEMPLATE,
        "DROP TEXT SEARCH TEMPLATE",
    ),
    (CMDTAG_DROP_TRANSFORM, "DROP TRANSFORM"),
    (CMDTAG_DROP_TRIGGER, "DROP TRIGGER"),
    (CMDTAG_DROP_TYPE, "DROP TYPE"),
    (CMDTAG_DROP_USER_MAPPING, "DROP USER MAPPING"),
    (CMDTAG_DROP_VIEW, "DROP VIEW"),
    (CMDTAG_EXECUTE, "EXECUTE"),
    (CMDTAG_EXPLAIN, "EXPLAIN"),
    (CMDTAG_FETCH, "FETCH"),
    (CMDTAG_GRANT, "GRANT"),
    (CMDTAG_GRANT_ROLE, "GRANT ROLE"),
    (CMDTAG_IMPORT_FOREIGN_SCHEMA, "IMPORT FOREIGN SCHEMA"),
    (CMDTAG_INSERT, "INSERT"),
    (CMDTAG_LISTEN, "LISTEN"),
    (CMDTAG_LOAD, "LOAD"),
    (CMDTAG_LOCK_TABLE, "LOCK TABLE"),
    (CMDTAG_LOGIN, "LOGIN"),
    (CMDTAG_MERGE, "MERGE"),
    (CMDTAG_MOVE, "MOVE"),
    (CMDTAG_NOTIFY, "NOTIFY"),
    (CMDTAG_PREPARE, "PREPARE"),
    (CMDTAG_PREPARE_TRANSACTION, "PREPARE TRANSACTION"),
    (CMDTAG_REASSIGN_OWNED, "REASSIGN OWNED"),
    (
        CMDTAG_REFRESH_MATERIALIZED_VIEW,
        "REFRESH MATERIALIZED VIEW",
    ),
    (CMDTAG_REINDEX, "REINDEX"),
    (CMDTAG_RELEASE, "RELEASE"),
    (CMDTAG_RESET, "RESET"),
    (CMDTAG_REVOKE, "REVOKE"),
    (CMDTAG_REVOKE_ROLE, "REVOKE ROLE"),
    (CMDTAG_ROLLBACK, "ROLLBACK"),
    (CMDTAG_ROLLBACK_PREPARED, "ROLLBACK PREPARED"),
    (CMDTAG_SAVEPOINT, "SAVEPOINT"),
    (CMDTAG_SECURITY_LABEL, "SECURITY LABEL"),
    (CMDTAG_SELECT, "SELECT"),
    (CMDTAG_SELECT_FOR_KEY_SHARE, "SELECT FOR KEY SHARE"),
    (CMDTAG_SELECT_FOR_NO_KEY_UPDATE, "SELECT FOR NO KEY UPDATE"),
    (CMDTAG_SELECT_FOR_SHARE, "SELECT FOR SHARE"),
    (CMDTAG_SELECT_FOR_UPDATE, "SELECT FOR UPDATE"),
    (CMDTAG_SELECT_INTO, "SELECT INTO"),
    (CMDTAG_SET, "SET"),
    (CMDTAG_SET_CONSTRAINTS, "SET CONSTRAINTS"),
    (CMDTAG_SHOW, "SHOW"),
    (CMDTAG_START_TRANSACTION, "START TRANSACTION"),
    (CMDTAG_TRUNCATE_TABLE, "TRUNCATE TABLE"),
    (CMDTAG_UNLISTEN, "UNLISTEN"),
    (CMDTAG_UPDATE, "UPDATE"),
    (CMDTAG_VACUUM, "VACUUM"),
];

// tcop/utility.h read-only classification flags.
pub const COMMAND_OK_IN_READ_ONLY_TXN: i32 = 0x0001;
pub const COMMAND_OK_IN_PARALLEL_MODE: i32 = 0x0002;
pub const COMMAND_OK_IN_RECOVERY: i32 = 0x0004;
pub const COMMAND_IS_STRICTLY_READ_ONLY: i32 =
    COMMAND_OK_IN_READ_ONLY_TXN | COMMAND_OK_IN_RECOVERY | COMMAND_OK_IN_PARALLEL_MODE;
pub const COMMAND_IS_NOT_READ_ONLY: i32 = 0;
