[package]
name = "heaptoast"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_nbtree = { path = "../../../../_support/types/types_nbtree" }
types_rel = { path = "../../../../_support/types/rel" }
types_scan = { path = "../../../../_support/types/types_scan" }
types_storage = { path = "../../../../_support/types/types_storage" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
pglz = { path = "../../../../common/pglz" }
lz4_flex = "0.11"
init_small = { path = "../../../utils/init/init_small" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
heaptuple = { path = "../../common/heaptuple" }
detoast = { path = "../../common/detoast" }
detoast_seams = { path = "../../common/detoast_seams" }
toastdesc = { path = "../../common/toastdesc" }
toast_internals_seams = { path = "../../common/toast_internals_seams" }
heaptoast_seams = { path = "../heaptoast_seams" }
heapam = { path = "../heapam" }
table = { path = "../../table/table" }
genam = { path = "../../index/genam" }
indexam = { path = "../../index/indexam" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
adt_scalar = { path = "../../../utils/adt/scalar" }
adt_int = { path = "../../../utils/adt/int" }
snapmgr = { path = "../../../utils/time/snapmgr" }
relcache_seams = { path = "../../../utils/cache/relcache_seams" }
catalog_seams = { path = "../../../catalog/catalog_seams" }
xact_seams = { path = "../../transam/xact_seams" }
types_snapshot = { path = "../../../../_support/types/snapshot" }

[dev-dependencies]
test_boot = { path = "../../../../_support/test_boot" }
bufmgr_seams = { path = "../../../storage/buffer/bufmgr_seams" }
heapam_visibility_seams = { path = "../heapam_visibility_seams" }
combocid_seams = { path = "../../../utils/time/combocid_seams" }
multixact_seams = { path = "../../transam/multixact_seams" }
predicate_seams = { path = "../../../storage/lmgr/predicate_seams" }
pruneheap_seams = { path = "../pruneheap_seams" }
procarray_seams = { path = "../../../storage/ipc/procarray_seams" }
freespace_seams = { path = "../../../storage/freespace/freespace_seams" }
xloginsert_seams = { path = "../../transam/xloginsert_seams" }
transam_xlog_seams = { path = "../../transam/transam_xlog_seams" }
miscinit_seams = { path = "../../../utils/init/miscinit_seams" }
relation_seams = { path = "../../common/relation_seams" }
tableam_vocab = { path = "../../table/tableam_vocab" }
nbt_compare = { path = "../../nbtree/compare" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
